/**
 * GENERATED FILE — do not edit by hand.
 *
 * Produced by `node scripts/placement/port-item-bank.mjs` from
 * `scripts/placement/source-item-bank.md` (the upstream CASA placement-test
 * teacher review book). Re-run the script instead of patching this file, or the
 * next port silently reverts your change.
 *
 * SERVER ONLY. This module carries answer keys and, for listening items,
 * protected transcripts. It must never be imported from a `'use client'`
 * module — `src/lib/placement/__tests__/answer-containment.test.ts` enforces
 * that. Client payloads are produced by `src/lib/placement/sanitise.ts`.
 */

import type { PlacementProductionPrompt, PlacementRubric } from '@/lib/placement/types';

export const PLACEMENT_WRITING_PROMPTS: readonly PlacementProductionPrompt[] = [
  {
    "id": "WR-A1-001",
    "kind": "writing",
    "title": "Später zum Deutschkurs",
    "targetLevel": "A1",
    "bands": ["A1.1", "A1.2"],
    "suggestedWords": {
      "min": 30,
      "max": 50,
    },
    "instruction": "Sie kommen heute später zum Deutschkurs. Schreiben Sie Ihrer Lehrerin oder Ihrem Lehrer eine kurze Nachricht.",
    "requiredContent": ["Begrüßen Sie die Person.", "Schreiben Sie, warum Sie später kommen.", "Schreiben Sie, wann Sie ungefähr da sind.", "Verabschieden Sie sich."],
    "sourceText": null,
    "reviewFocus": ["task_fulfilment", "basic_sentence_control", "intelligibility"],
  },
  {
    "id": "WR-A1-002",
    "kind": "writing",
    "title": "Kaffee mit einer Nachbarin",
    "targetLevel": "A1",
    "bands": ["A1.1", "A1.2"],
    "suggestedWords": {
      "min": 30,
      "max": 50,
    },
    "instruction": "Sie möchten Ihre Nachbarin zu einem Kaffee einladen. Schreiben Sie eine kurze Nachricht.",
    "requiredContent": ["Machen Sie eine Einladung.", "Nennen Sie einen Tag und eine Uhrzeit.", "Nennen Sie einen Ort.", "Bitten Sie um eine Antwort."],
    "sourceText": null,
    "reviewFocus": ["task_fulfilment", "time_and_place", "basic_politeness"],
  },
  {
    "id": "WR-A1-003",
    "kind": "writing",
    "title": "Frage an die Sprachschule",
    "targetLevel": "A1",
    "bands": ["A1.1", "A1.2"],
    "suggestedWords": {
      "min": 30,
      "max": 55,
    },
    "instruction": "Schreiben Sie eine kurze Nachricht an eine Sprachschule und fragen Sie nach einem Deutschkurs.",
    "requiredContent": ["Schreiben Sie, welchen Kurs Sie suchen.", "Fragen Sie nach dem Startdatum.", "Fragen Sie nach der Uhrzeit.", "Nennen Sie Ihren Namen."],
    "sourceText": null,
    "reviewFocus": ["task_fulfilment", "questions", "basic_register"],
  },
  {
    "id": "WR-A2-001",
    "kind": "writing",
    "title": "Termin verschieben",
    "targetLevel": "A2",
    "bands": ["A2.1", "A2.2"],
    "suggestedWords": {
      "min": 60,
      "max": 90,
    },
    "instruction": "Sie können zu einem vereinbarten Termin nicht kommen. Schreiben Sie der anderen Person eine Nachricht.",
    "requiredContent": ["Entschuldigen Sie sich.", "Nennen Sie einen Grund.", "Schlagen Sie einen neuen Termin vor.", "Bitten Sie um eine Bestätigung."],
    "sourceText": null,
    "reviewFocus": ["task_fulfilment", "connected_sentences", "polite_request"],
  },
  {
    "id": "WR-A2-002",
    "kind": "writing",
    "title": "Problem in der Wohnung",
    "targetLevel": "A2",
    "bands": ["A2.1", "A2.2"],
    "suggestedWords": {
      "min": 60,
      "max": 90,
    },
    "instruction": "In Ihrer Wohnung funktioniert seit gestern die Heizung nicht. Schreiben Sie Ihrer Vermieterin oder Ihrem Vermieter.",
    "requiredContent": ["Beschreiben Sie das Problem.", "Schreiben Sie, seit wann es besteht.", "Erklären Sie, warum es dringend ist.", "Bitten Sie um einen Reparaturtermin."],
    "sourceText": null,
    "reviewFocus": ["description", "time_reference", "request"],
  },
  {
    "id": "WR-A2-003",
    "kind": "writing",
    "title": "Plan für das Wochenende",
    "targetLevel": "A2",
    "bands": ["A2.1", "A2.2"],
    "suggestedWords": {
      "min": 60,
      "max": 90,
    },
    "instruction": "Eine Freundin schlägt einen Ausflug am Wochenende vor. Antworten Sie ihr.",
    "requiredContent": ["Reagieren Sie auf den Vorschlag.", "Sagen Sie, welcher Tag für Sie passt.", "Nennen Sie, was Sie gern machen möchten.", "Begründen Sie Ihre Wahl kurz."],
    "sourceText": null,
    "reviewFocus": ["interaction", "preference", "reason"],
  },
  {
    "id": "WR-B1-001",
    "kind": "writing",
    "title": "Arbeitszeit und Sprachkurs",
    "targetLevel": "B1",
    "bands": ["B1.1", "B1.2"],
    "suggestedWords": {
      "min": 100,
      "max": 130,
    },
    "instruction": "Ihr neuer Sprachkurs beginnt früher als geplant und überschneidet sich einmal pro Woche mit Ihrer Arbeitszeit. Schreiben Sie Ihrer Teamleitung.",
    "requiredContent": ["Erklären Sie die Situation.", "Beschreiben Sie, an welchem Tag das Problem besteht.", "Schlagen Sie eine praktische Lösung vor.", "Bitten Sie um ein Gespräch oder eine Rückmeldung."],
    "sourceText": null,
    "reviewFocus": ["coherence", "explanation", "solution", "appropriate_register"],
  },
  {
    "id": "WR-B1-002",
    "kind": "writing",
    "title": "Beschädigte Online-Bestellung",
    "targetLevel": "B1",
    "bands": ["B1.1", "B1.2"],
    "suggestedWords": {
      "min": 100,
      "max": 130,
    },
    "instruction": "Sie haben einen Schreibtischstuhl bestellt. Ein Teil ist beschädigt, ein anderes Teil fehlt. Schreiben Sie dem Kundenservice.",
    "requiredContent": ["Nennen Sie die Bestellung.", "Beschreiben Sie beide Probleme.", "Schreiben Sie, welche Lösung Sie erwarten.", "Setzen Sie eine angemessene Frist für die Antwort."],
    "sourceText": null,
    "reviewFocus": ["task_fulfilment", "detail", "complaint_register", "cohesion"],
  },
  {
    "id": "WR-B1-003",
    "kind": "writing",
    "title": "Handyfreie Lernzeit",
    "targetLevel": "B1",
    "bands": ["B1.1", "B1.2"],
    "suggestedWords": {
      "min": 100,
      "max": 140,
    },
    "instruction": "In Ihrem Kurs wird überlegt, während bestimmter Lernphasen alle Handys wegzulegen. Schreiben Sie Ihre Meinung für das Kursforum.",
    "requiredContent": ["Nennen Sie Ihre Position.", "Geben Sie mindestens einen Vorteil an.", "Nennen Sie ein mögliches Problem.", "Machen Sie einen Kompromissvorschlag."],
    "sourceText": null,
    "reviewFocus": ["opinion", "reasoning", "balance", "cohesion"],
  },
  {
    "id": "WR-B1P-001",
    "kind": "writing",
    "title": "Regeln für hybride Besprechungen",
    "targetLevel": "B1_PLUS",
    "bands": ["B1+"],
    "suggestedWords": {
      "min": 130,
      "max": 170,
    },
    "instruction": "Ihr Team arbeitet teilweise im Büro und teilweise von zu Hause. Schreiben Sie eine Empfehlung für zukünftige Besprechungen.",
    "requiredContent": ["Beschreiben Sie das aktuelle Problem.", "Schlagen Sie zwei konkrete Regeln vor.", "Begründen Sie die Regeln.", "Nennen Sie eine mögliche Ausnahme."],
    "sourceText": null,
    "reviewFocus": ["sentence_stability", "argument_structure", "functional_phrases", "register"],
  },
  {
    "id": "WR-B1P-002",
    "kind": "writing",
    "title": "Vorschlag für eine Fortbildung",
    "targetLevel": "B1_PLUS",
    "bands": ["B1+"],
    "suggestedWords": {
      "min": 130,
      "max": 170,
    },
    "instruction": "Die Leitung plant eine eintägige Pflichtschulung. Viele Teilzeitkräfte können an diesem Tag nicht teilnehmen. Schreiben Sie eine Rückmeldung.",
    "requiredContent": ["Erkennen Sie das Ziel der Schulung an.", "Erklären Sie das organisatorische Problem.", "Schlagen Sie eine Alternative vor.", "Formulieren Sie Bedingungen für eine gute Lösung."],
    "sourceText": null,
    "reviewFocus": ["balanced_response", "cohesion", "formal_register", "range"],
  },
  {
    "id": "WR-B1P-003",
    "kind": "writing",
    "title": "Nutzung eines Nachbarschaftsraums",
    "targetLevel": "B1_PLUS",
    "bands": ["B1+"],
    "suggestedWords": {
      "min": 130,
      "max": 180,
    },
    "instruction": "Ein freier Raum im Stadtteil kann entweder als ruhiger Lernraum oder als Treffpunkt genutzt werden. Schreiben Sie eine begründete Empfehlung.",
    "requiredContent": ["Vergleichen Sie beide Möglichkeiten.", "Nennen Sie die Bedürfnisse verschiedener Gruppen.", "Treffen Sie eine begründete Entscheidung.", "Schlagen Sie vor, wie Nachteile begrenzt werden können."],
    "sourceText": null,
    "reviewFocus": ["comparison", "argumentation", "lexical_range", "cohesion"],
  },
  {
    "id": "WR-B2-001",
    "kind": "writing",
    "title": "Flexible Arbeit organisieren",
    "targetLevel": "B2",
    "bands": ["B2.1", "B2.2"],
    "suggestedWords": {
      "min": 170,
      "max": 220,
    },
    "instruction": "Ein Unternehmen erwägt entweder feste Homeoffice-Tage für alle oder flexible Absprachen in jedem Team. Schreiben Sie eine Empfehlung an die Geschäftsleitung.",
    "requiredContent": ["Vergleichen Sie beide Modelle.", "Bewerten Sie Auswirkungen auf Zusammenarbeit und Planbarkeit.", "Beziehen Sie unterschiedliche Tätigkeiten ein.", "Empfehlen Sie eine Lösung mit Bedingungen."],
    "sourceText": null,
    "reviewFocus": ["structured_argument", "nuance", "register", "range_and_control"],
  },
  {
    "id": "WR-B2-002",
    "kind": "writing",
    "title": "Kostenloser Nahverkehr",
    "targetLevel": "B2",
    "bands": ["B2.1", "B2.2"],
    "suggestedWords": {
      "min": 170,
      "max": 230,
    },
    "instruction": "Ihre Stadt diskutiert, den Nahverkehr an Samstagen kostenlos anzubieten. Verfassen Sie einen Beitrag für eine öffentliche Anhörung.",
    "requiredContent": ["Bewerten Sie das Ziel der Maßnahme.", "Erörtern Sie mögliche Vorteile.", "Nennen Sie mindestens eine Grenze oder Nebenwirkung.", "Schlagen Sie vor, wie der Erfolg gemessen werden sollte."],
    "sourceText": null,
    "reviewFocus": ["argumentation", "qualification", "cohesion", "public_register"],
  },
  {
    "id": "WR-B2-003",
    "kind": "writing",
    "title": "Automatische Rückmeldungen beim Lernen",
    "targetLevel": "B2",
    "bands": ["B2.1", "B2.2"],
    "suggestedWords": {
      "min": 170,
      "max": 220,
    },
    "instruction": "Lesen Sie die kurze Aussage und nehmen Sie begründet Stellung.",
    "requiredContent": ["Fassen Sie die Kernaussage knapp zusammen.", "Nennen Sie einen sinnvollen Einsatzbereich.", "Erklären Sie eine wichtige Grenze.", "Formulieren Sie eine ausgewogene Empfehlung."],
    "sourceText": "„Automatische Rückmeldungen ermöglichen häufigeres Üben, sollten aber pädagogische Entscheidungen nicht ersetzen.“",
    "reviewFocus": ["summary", "source_integration", "nuanced_position", "language_control"],
  },
  {
    "id": "WR-C1-001",
    "kind": "writing",
    "title": "Digitale Bürgerbeteiligung",
    "targetLevel": "C1",
    "bands": ["C1.1", "C1.2"],
    "suggestedWords": {
      "min": 220,
      "max": 280,
    },
    "instruction": "Verfassen Sie eine kurze Stellungnahme, die die beiden Positionen zusammenführt und eine Empfehlung entwickelt.",
    "requiredContent": ["Arbeiten Sie die unterschiedliche Schwerpunktsetzung beider Positionen heraus.", "Bewerten Sie Reichweite und Grenzen digitaler Beteiligung.", "Entwickeln Sie Kriterien für ein glaubwürdiges Verfahren.", "Formulieren Sie eine differenzierte Empfehlung."],
    "sourceText": "Position A: Digitale Beteiligung senkt zeitliche und räumliche Hürden.\nPosition B: Digitale Verfahren erreichen nicht automatisch Gruppen mit geringerer technischer Erfahrung und können bestehende Unterschiede verstärken.",
    "reviewFocus": ["synthesis", "precision", "cohesion", "register", "nuance"],
  },
  {
    "id": "WR-C1-002",
    "kind": "writing",
    "title": "Qualität in der Bildung messen",
    "targetLevel": "C1",
    "bands": ["C1.1", "C1.2"],
    "suggestedWords": {
      "min": 220,
      "max": 290,
    },
    "instruction": "Eine Bildungseinrichtung möchte Qualität künftig stärker mit Kennzahlen steuern. Schreiben Sie ein kurzes internes Memorandum.",
    "requiredContent": ["Erklären Sie den Nutzen von Kennzahlen.", "Analysieren Sie mögliche Fehlanreize.", "Unterscheiden Sie messbare Ergebnisse von schwer messbaren Qualitätsaspekten.", "Empfehlen Sie ein verantwortliches Vorgehen."],
    "sourceText": null,
    "reviewFocus": ["conceptual_precision", "argument_structure", "institutional_register", "qualification"],
  },
  {
    "id": "WR-C1-003",
    "kind": "writing",
    "title": "KI beim Sprachenlernen",
    "targetLevel": "C1",
    "bands": ["C1.1", "C1.2"],
    "suggestedWords": {
      "min": 220,
      "max": 290,
    },
    "instruction": "Verfassen Sie eine differenzierte Stellungnahme für eine Fachkonferenz.",
    "requiredContent": ["Ordnen Sie mögliche Vorteile ein.", "Analysieren Sie Grenzen bei Angemessenheit und Bewertung.", "Berücksichtigen Sie Transparenz und menschliche Verantwortung.", "Entwickeln Sie ein begründetes Einsatzmodell."],
    "sourceText": null,
    "reviewFocus": ["complex_argument", "lexical_precision", "cohesion", "formal_register"],
  },
] as const;

export const PLACEMENT_SPEAKING_PROMPTS: readonly PlacementProductionPrompt[] = [
  {
    "id": "SP-A1-001",
    "kind": "speaking",
    "title": "Sich vorstellen",
    "targetLevel": "A1",
    "bands": ["A1.1", "A1.2"],
    "preparationSeconds": 30,
    "responseSeconds": 60,
    "instruction": "Stellen Sie sich kurz vor.",
    "requiredContent": ["Sagen Sie Ihren Namen.", "Sagen Sie, wo Sie wohnen.", "Sagen Sie, welche Sprachen Sie sprechen.", "Sagen Sie, warum Sie Deutsch lernen."],
    "sourceText": null,
    "reviewFocus": ["intelligibility", "basic_fluency", "task_fulfilment"],
  },
  {
    "id": "SP-A1-002",
    "kind": "speaking",
    "title": "Mein Tagesablauf",
    "targetLevel": "A1",
    "bands": ["A1.1", "A1.2"],
    "preparationSeconds": 30,
    "responseSeconds": 60,
    "instruction": "Erzählen Sie kurz von einem normalen Tag.",
    "requiredContent": ["Wann beginnt Ihr Tag?", "Was machen Sie vormittags?", "Was machen Sie abends?"],
    "sourceText": null,
    "reviewFocus": ["basic_sequence", "time_expressions", "intelligibility"],
  },
  {
    "id": "SP-A2-001",
    "kind": "speaking",
    "title": "Ein schöner Ausflug",
    "targetLevel": "A2",
    "bands": ["A2.1", "A2.2"],
    "preparationSeconds": 45,
    "responseSeconds": 90,
    "instruction": "Erzählen Sie von einem Ausflug oder einer Reise.",
    "requiredContent": ["Wohin sind Sie gefahren?", "Mit wem waren Sie dort?", "Was haben Sie gemacht?", "Wie hat es Ihnen gefallen?"],
    "sourceText": null,
    "reviewFocus": ["past_narrative", "connected_speech", "intelligibility"],
  },
  {
    "id": "SP-A2-002",
    "kind": "speaking",
    "title": "Einen Termin ändern",
    "targetLevel": "A2",
    "bands": ["A2.1", "A2.2"],
    "preparationSeconds": 30,
    "responseSeconds": 75,
    "instruction": "Sprechen Sie eine kurze Nachricht: Sie müssen einen Termin ändern.",
    "requiredContent": ["Nennen Sie den Termin.", "Erklären Sie kurz den Grund.", "Schlagen Sie eine neue Zeit vor.", "Bitten Sie um Antwort."],
    "sourceText": null,
    "reviewFocus": ["functional_language", "clarity", "politeness"],
  },
  {
    "id": "SP-B1-001",
    "kind": "speaking",
    "title": "Eine Veränderung erklären",
    "targetLevel": "B1",
    "bands": ["B1.1", "B1.2"],
    "preparationSeconds": 60,
    "responseSeconds": 120,
    "instruction": "Erzählen Sie von einer Veränderung in Ihrem Alltag, bei der Sie sich an etwas Neues gewöhnen mussten.",
    "requiredContent": ["Beschreiben Sie die Situation.", "Erklären Sie die Schwierigkeit.", "Sagen Sie, was Ihnen geholfen hat.", "Bewerten Sie das Ergebnis."],
    "sourceText": null,
    "reviewFocus": ["narrative", "explanation", "fluency", "coherence"],
  },
  {
    "id": "SP-B1-002",
    "kind": "speaking",
    "title": "Eine praktische Lösung vorschlagen",
    "targetLevel": "B1",
    "bands": ["B1.1", "B1.2"],
    "preparationSeconds": 60,
    "responseSeconds": 120,
    "instruction": "In Ihrem Kurs kommen viele Personen zu spät, weil der Raum schwer zu finden ist. Schlagen Sie eine Lösung vor.",
    "requiredContent": ["Beschreiben Sie das Problem.", "Machen Sie mindestens zwei Vorschläge.", "Begründen Sie Ihre bevorzugte Lösung."],
    "sourceText": null,
    "reviewFocus": ["problem_solution", "reasoning", "connected_speech"],
  },
  {
    "id": "SP-B1P-001",
    "kind": "speaking",
    "title": "Besprechungen verbessern",
    "targetLevel": "B1_PLUS",
    "bands": ["B1+"],
    "preparationSeconds": 60,
    "responseSeconds": 135,
    "instruction": "Ihr Team hält viele Besprechungen für zu lang. Geben Sie eine strukturierte Empfehlung.",
    "requiredContent": ["Analysieren Sie mögliche Ursachen.", "Schlagen Sie konkrete Änderungen vor.", "Nennen Sie eine Situation, in der eine längere Besprechung sinnvoll bleibt."],
    "sourceText": null,
    "reviewFocus": ["structure", "range", "sentence_stability", "qualification"],
  },
  {
    "id": "SP-B1P-002",
    "kind": "speaking",
    "title": "Lernangebot bewerten",
    "targetLevel": "B1_PLUS",
    "bands": ["B1+"],
    "preparationSeconds": 60,
    "responseSeconds": 135,
    "instruction": "Bewerten Sie, ob ein Sprachkurs mehr Online-Unterricht anbieten sollte.",
    "requiredContent": ["Nennen Sie Vorteile.", "Nennen Sie mögliche Nachteile.", "Berücksichtigen Sie unterschiedliche Lernende.", "Formulieren Sie einen Kompromiss."],
    "sourceText": null,
    "reviewFocus": ["balanced_argument", "functional_phrases", "fluency"],
  },
  {
    "id": "SP-B2-001",
    "kind": "speaking",
    "title": "Eine Maßnahme abwägen",
    "targetLevel": "B2",
    "bands": ["B2.1", "B2.2"],
    "preparationSeconds": 75,
    "responseSeconds": 150,
    "instruction": "Eine Stadt möchte Parkplätze im Zentrum reduzieren und mehr Platz für Fahrräder schaffen. Nehmen Sie differenziert Stellung.",
    "requiredContent": ["Bewerten Sie das Ziel.", "Berücksichtigen Sie verschiedene betroffene Gruppen.", "Nennen Sie Risiken oder Bedingungen.", "Entwickeln Sie eine Empfehlung."],
    "sourceText": null,
    "reviewFocus": ["nuance", "argumentation", "range_and_control", "cohesion"],
  },
  {
    "id": "SP-B2-002",
    "kind": "speaking",
    "title": "Technische Unterstützung im Alltag",
    "targetLevel": "B2",
    "bands": ["B2.1", "B2.2"],
    "preparationSeconds": 75,
    "responseSeconds": 150,
    "instruction": "Erörtern Sie, wann automatische Entscheidungen hilfreich sind und wann ein Mensch entscheiden sollte.",
    "requiredContent": ["Nennen Sie geeignete Beispiele.", "Erklären Sie Grenzen.", "Berücksichtigen Sie Verantwortung und Transparenz.", "Formulieren Sie ein Prinzip für den Einsatz."],
    "sourceText": null,
    "reviewFocus": ["abstract_reasoning", "precision", "structured_delivery"],
  },
  {
    "id": "SP-C1-001",
    "kind": "speaking",
    "title": "Erfolg eines Pilotprojekts beurteilen",
    "targetLevel": "C1",
    "bands": ["C1.1", "C1.2"],
    "preparationSeconds": 90,
    "responseSeconds": 180,
    "instruction": "Ein Pilotprojekt erhält positive Rückmeldungen, wurde aber nur von freiwilligen, besonders motivierten Gruppen getestet. Bewerten Sie die Aussagekraft der Ergebnisse.",
    "requiredContent": ["Analysieren Sie mögliche Verzerrungen.", "Unterscheiden Sie Rückmeldung und belastbare Wirkung.", "Schlagen Sie ein verbessertes weiteres Vorgehen vor.", "Formulieren Sie eine vorläufige Schlussfolgerung."],
    "sourceText": null,
    "reviewFocus": ["methodological_reasoning", "precision", "nuance", "cohesion"],
  },
  {
    "id": "SP-C1-002",
    "kind": "speaking",
    "title": "Offenheit und Verantwortung",
    "targetLevel": "C1",
    "bands": ["C1.1", "C1.2"],
    "preparationSeconds": 90,
    "responseSeconds": 180,
    "instruction": "Erörtern Sie die Aussage: „Eine gute Fehlerkultur braucht Offenheit, darf aber Verantwortlichkeit nicht auflösen.“",
    "requiredContent": ["Deuten Sie die Aussage.", "Unterscheiden Sie verschiedene Arten von Fehlern.", "Analysieren Sie institutionelle Bedingungen.", "Entwickeln Sie eine differenzierte Position."],
    "sourceText": null,
    "reviewFocus": ["conceptual_argument", "register", "range", "qualification"],
  },
] as const;

export const PLACEMENT_WRITING_RUBRIC: PlacementRubric = {
  "id": "RUBRIC-WRITING-V1",
  "version": 1,
  "criteria": [
    {
      "key": "task_fulfilment",
      "label": "Aufgabenerfüllung und kommunikative Wirkung",
      "descriptors": {
        "0": "Keine verwertbare Leistung oder nicht zur Aufgabe.",
        "1": "Nur einzelne Punkte erkennbar; Zweck meist nicht erreicht.",
        "2": "Wesentliche Punkte teilweise erfüllt; Botschaft mit Lücken verständlich.",
        "3": "Aufgabe weitgehend vollständig und situationsangemessen erfüllt.",
        "4": "Aufgabe vollständig, präzise und kommunikativ wirksam erfüllt.",
      },
    },
    {
      "key": "coherence",
      "label": "Aufbau, Kohärenz und Kohäsion",
      "descriptors": {
        "0": "Keine zusammenhängende Textleistung.",
        "1": "Überwiegend isolierte Wörter oder Sätze; Beziehungen oft unklar.",
        "2": "Einfache Verbindung der Gedanken, jedoch mit Brüchen oder Wiederholungen.",
        "3": "Klar gegliedert und überwiegend gut verbunden.",
        "4": "Durchgehend klar, flexibel und dem Zweck entsprechend organisiert.",
      },
    },
    {
      "key": "vocabulary",
      "label": "Wortschatz: Spektrum und Kontrolle",
      "descriptors": {
        "0": "Keine bewertbare lexikalische Leistung.",
        "1": "Sehr begrenzt; häufige Lücken verhindern die Aussage.",
        "2": "Ausreichend für Grundinhalte; Umschreibungen und unpassende Wahl treten auf.",
        "3": "Gutes Spektrum für die Aufgabe; gelegentliche unpassende Wahl stört kaum.",
        "4": "Breites, präzises und registergerechtes Spektrum mit flexibler Formulierung.",
      },
    },
    {
      "key": "grammar",
      "label": "Grammatik: Spektrum und Korrektheit",
      "descriptors": {
        "0": "Keine bewertbare grammatische Leistung.",
        "1": "Nur sehr einfache Strukturen; Fehler behindern häufig das Verständnis.",
        "2": "Einfache Strukturen überwiegend kontrolliert; komplexere Versuche fehleranfällig.",
        "3": "Angemessenes Spektrum; Fehler beeinträchtigen die Verständlichkeit kaum.",
        "4": "Breites Spektrum mit hoher Kontrolle; seltene Fehler sind unauffällig.",
      },
    },
  ],
} as const;

export const PLACEMENT_SPEAKING_RUBRIC: PlacementRubric = {
  "id": "RUBRIC-SPEAKING-V1",
  "version": 1,
  "criteria": [
    {
      "key": "task_effectiveness",
      "label": "Aufgabenerfüllung und kommunikative Wirkung",
      "descriptors": {
        "0": "Keine verwertbare Leistung.",
        "1": "Nur einzelne relevante Aussagen; Zweck kaum erreicht.",
        "2": "Kernaufgabe teilweise erfüllt; Nachfragen wären häufig nötig.",
        "3": "Aufgabe weitgehend klar und situationsangemessen erfüllt.",
        "4": "Aufgabe vollständig, präzise und wirkungsvoll erfüllt.",
      },
    },
    {
      "key": "fluency_organisation",
      "label": "Flüssigkeit und Organisation",
      "descriptors": {
        "0": "Keine zusammenhängende Leistung.",
        "1": "Sehr viele lange Pausen; nur kurze Fragmente.",
        "2": "Einfache zusammenhängende Abschnitte, aber merkliche Suche und Brüche.",
        "3": "Überwiegend flüssig und klar organisiert; gelegentliche Suche.",
        "4": "Flüssig, flexibel und überzeugend organisiert.",
      },
    },
    {
      "key": "range_control",
      "label": "Wortschatz und Grammatik: Spektrum und Kontrolle",
      "descriptors": {
        "0": "Keine bewertbare sprachliche Leistung.",
        "1": "Sehr begrenzte Mittel; Fehler behindern häufig.",
        "2": "Ausreichende Mittel für Grundinhalte; komplexere Aussagen instabil.",
        "3": "Angemessenes Spektrum mit guter Kontrolle; Fehler stören wenig.",
        "4": "Breites und präzises Spektrum mit hoher Kontrolle und Registerbewusstsein.",
      },
    },
    {
      "key": "pronunciation_intelligibility",
      "label": "Aussprache und Verständlichkeit",
      "descriptors": {
        "0": "Nicht verständlich oder keine Aufnahme.",
        "1": "Häufig schwer verständlich; große Höranstrengung nötig.",
        "2": "Im Allgemeinen verständlich, trotz deutlicher Einflüsse und einzelner Unklarheiten.",
        "3": "Klar verständlich; Prosodie unterstützt meist die Aussage.",
        "4": "Durchgehend klar und flexibel verständlich; Akzent ist kein Bewertungskriterium.",
      },
    },
  ],
} as const;
