/**
 * GENERATED FILE — do not edit by hand.
 *
 * Produced by `node scripts/placement/port-item-bank.mjs` from
 * `scripts/placement/source-item-bank.md` (the upstream CASA placement-test
 * teacher review book). Re-run the script instead of patching this file, or the
 * next port silently reverts your change.
 *
 * SERVER ONLY. This module carries answer keys and, for listening items,
 * protected transcripts. It must never be imported from a `'use client'`
 * module — `src/lib/placement/__tests__/answer-containment.test.ts` enforces
 * that. Client payloads are produced by `src/lib/placement/sanitise.ts`.
 */

import type { PlacementStimulus } from '@/lib/placement/types';

export const PLACEMENT_STIMULI: readonly PlacementStimulus[] = [
  {
    "id": "STIM-RD-ROUTER-A1-001",
    "kind": "reading",
    "title": "Öffnungszeiten",
    "text": "Praxis Dr. König\nHeute nur bis 12 Uhr geöffnet.\nAm Nachmittag geschlossen.",
  },
  {
    "id": "STIM-LS-ROUTER-A1-001",
    "kind": "listening",
    "title": "Kursbeginn",
    "audioPath": "/placement-audio/v1/stim-ls-router-a1-001.mp3",
    "maxPlays": 2,
    "transcript": "Der Deutschkurs beginnt morgen nicht um neun, sondern erst um halb zehn.",
    "recordingDirection": "Eine Sprecherin, langsam und deutlich, natürliche Betonung auf „nicht um neun“ und „halb zehn“. Pause nach dem ersten Satz.",
  },
  {
    "id": "STIM-RD-ROUTER-A2-001",
    "kind": "reading",
    "title": "Terminänderung",
    "text": "Hallo Elena, unser Termin am Donnerstag um 14 Uhr muss leider ausfallen. Ich kann am selben Tag ab 15:30 Uhr oder am Freitagvormittag. Passt dir einer der Termine? Viele Grüße, Miriam",
  },
  {
    "id": "STIM-LS-ROUTER-A2-001",
    "kind": "listening",
    "title": "Reklamation",
    "audioPath": "/placement-audio/v1/stim-ls-router-a2-001.mp3",
    "maxPlays": 2,
    "transcript": "Kundin: Guten Tag. Ich habe diese Jacke gestern gekauft, aber der Reißverschluss ist schon kaputt. Kann ich sie umtauschen? Verkäufer: Natürlich. Haben Sie den Kassenbon dabei?",
    "recordingDirection": "Zwei Stimmen, normales A2-Tempo, ruhiger Laden, keine Hintergrundgeräusche.",
  },
  {
    "id": "STIM-RD-ROUTER-B1-001",
    "kind": "reading",
    "title": "Flexible Arbeitszeit",
    "text": "Seit drei Monaten können die Beschäftigten der Firma Nordlicht ihren Arbeitstag zwischen 7 und 10 Uhr beginnen. Die Wochenarbeitszeit bleibt gleich. Viele Eltern nutzen die neue Regelung, um morgens mehr Zeit für ihre Familie zu haben. Die Geschäftsleitung berichtet zugleich, dass Besprechungen nun genauer geplant werden müssen.",
  },
  {
    "id": "STIM-LS-ROUTER-B1-001",
    "kind": "listening",
    "title": "Nachricht an die Nachbarin",
    "audioPath": "/placement-audio/v1/stim-ls-router-b1-001.mp3",
    "maxPlays": 2,
    "transcript": "Hallo Frau Özdemir, hier ist Paul aus dem dritten Stock. Morgen kommt zwischen zwölf und vier ein Paket für mich. Ich bin leider im Büro. Könnten Sie es vielleicht annehmen? Ich hole es am Abend bei Ihnen ab. Wenn es nicht passt, ist das natürlich auch kein Problem. Vielen Dank!",
    "recordingDirection": "Eine männliche Stimme, freundliche natürliche Mailbox-Nachricht, klares Standarddeutsch.",
  },
  {
    "id": "STIM-RD-ROUTER-B2-001",
    "kind": "reading",
    "title": "Arbeiten von zu Hause",
    "text": "Homeoffice ist für viele Beschäftigte eine wichtige Entlastung. Daraus folgt jedoch nicht, dass das Büro überflüssig geworden ist. Gerade neue Kolleginnen und Kollegen profitieren von spontanen Gesprächen, die sich digital nur schwer planen lassen. Sinnvoller als eine starre Regel scheint deshalb eine Lösung, die Teams selbst an ihre Aufgaben anpassen können.",
  },
  {
    "id": "STIM-LS-ROUTER-B2-001",
    "kind": "listening",
    "title": "Lange Museumsabende",
    "audioPath": "/placement-audio/v1/stim-ls-router-b2-001.mp3",
    "maxPlays": 2,
    "transcript": "Moderatorin: Sie begrüßen also die geplanten langen Museumsabende? Direktor: Grundsätzlich ja. Wir erreichen damit Menschen, die tagsüber arbeiten. Allerdings darf man nicht so tun, als ließe sich das ohne zusätzliches Personal organisieren. Wenn die Finanzierung ungeklärt bleibt, wird aus einer guten Idee schnell eine Belastung für das Team.",
    "recordingDirection": "Zwei Stimmen, B2-Tempo. Direktor zustimmend, aber deutlich abwägend; keine Ironie.",
  },
  {
    "id": "STIM-RD-ROUTER-C1-001",
    "kind": "reading",
    "title": "Digitalisierung von Abläufen",
    "text": "Wer analoge Formulare lediglich auf einen Bildschirm überträgt, hat noch keinen Prozess digitalisiert. Der mögliche Gewinn entsteht erst, wenn Zuständigkeiten, Informationswege und unnötige Prüfschritte neu betrachtet werden. Das ist aufwendiger als die Anschaffung einer Software, erklärt aber auch, weshalb technisch einwandfreie Projekte organisatorisch scheitern können.",
  },
  {
    "id": "STIM-LS-ROUTER-C1-001",
    "kind": "listening",
    "title": "Bürgerbeteiligung",
    "audioPath": "/placement-audio/v1/stim-ls-router-c1-001.mp3",
    "maxPlays": 2,
    "transcript": "Expertin: Beteiligungsverfahren werden gelegentlich als Verzögerung wahrgenommen. Das ist nachvollziehbar, greift aber zu kurz. Ein früh geführter Konflikt kostet zunächst Zeit, kann später jedoch Entscheidungen stabilisieren. Entscheidend ist, ob die Beteiligung tatsächlich offen ist oder nur nachträglich Zustimmung erzeugen soll.",
    "recordingDirection": "Eine weibliche Stimme, ruhiges C1-Tempo, differenzierte Haltung, klare Kontraste.",
  },
  {
    "id": "STIM-RD-A1-001",
    "kind": "reading",
    "title": "Kursplan",
    "text": "Deutschkurs A1\nMontag und Mittwoch, 18:00–19:30 Uhr, Raum 4.\nDiese Woche beginnt der Kurs am Mittwoch ausnahmsweise erst um 18:30 Uhr.",
  },
  {
    "id": "STIM-RD-A1-002",
    "kind": "reading",
    "title": "Treffen im Café",
    "text": "Hallo Samira, ich bin schon im Café Central. Ich sitze draußen links neben der Tür. Bis gleich! Jonas",
  },
  {
    "id": "STIM-RD-A1-003",
    "kind": "reading",
    "title": "Öffnungszeit am Samstag",
    "text": "Supermarkt am Park\nAm Samstag wegen Inventur nur bis 14 Uhr geöffnet.\nAb Montag wieder normale Öffnungszeiten.",
  },
  {
    "id": "STIM-LS-A1-001",
    "kind": "listening",
    "title": "Termin in der Praxis",
    "audioPath": "/placement-audio/v1/stim-ls-a1-001.mp3",
    "maxPlays": 2,
    "transcript": "Guten Tag, hier ist die Praxis Weber. Ihr Termin ist am Dienstag um Viertel nach zehn. Bitte bringen Sie Ihre Versicherungskarte mit.",
    "recordingDirection": "Eine weibliche Stimme, langsam, deutlich. Kurze Pause zwischen Zeit und Bitte.",
  },
  {
    "id": "STIM-LS-A1-002",
    "kind": "listening",
    "title": "Bestellung in der Bäckerei",
    "audioPath": "/placement-audio/v1/stim-ls-a1-002.mp3",
    "maxPlays": 2,
    "transcript": "Kunde: Guten Morgen. Ich hätte gern zwei Brötchen und einen Kaffee, bitte. Verkäuferin: Gern. Das macht fünf Euro zwanzig.",
    "recordingDirection": "Zwei Stimmen, langsames natürliches A1-Tempo.",
  },
  {
    "id": "STIM-LS-A1-003",
    "kind": "listening",
    "title": "Wegbeschreibung",
    "audioPath": "/placement-audio/v1/stim-ls-a1-003.mp3",
    "maxPlays": 2,
    "transcript": "Am Bahnhof nehmen Sie den Bus Nummer vierundzwanzig. Fahren Sie vier Stationen und steigen Sie an der Haltestelle Theater aus.",
    "recordingDirection": "Eine Stimme, langsam und deutlich; Nummer und Haltestelle klar betonen.",
  },
  {
    "id": "STIM-RD-A2-001",
    "kind": "reading",
    "title": "Wasser wird abgestellt",
    "text": "Liebe Hausbewohnerinnen und Hausbewohner, am Dienstag wird das Wasser zwischen 9 und 12 Uhr abgestellt. Grund sind Reparaturen im Keller. Bitte denken Sie daran, vorher genug Wasser für den Vormittag bereitzustellen. Die Hausverwaltung",
  },
  {
    "id": "STIM-RD-A2-002",
    "kind": "reading",
    "title": "Zug fällt aus",
    "text": "Der Regionalzug RE 8 um 16:42 Uhr nach Bremerhaven fällt heute aus. Reisende können den Ersatzbus vor dem Haupteingang benutzen. Der Bus fährt um 16:55 Uhr ab und hält an allen Bahnhöfen der Strecke.",
  },
  {
    "id": "STIM-RD-A2-003",
    "kind": "reading",
    "title": "Schichttausch",
    "text": "Hallo Deniz, könntest du am Samstag meine Frühschicht von 7 bis 13 Uhr übernehmen? Ich habe einen wichtigen Termin. Dafür kann ich nächste Woche deine Spätschicht am Mittwoch machen. Gib mir bitte bis morgen Bescheid. Viele Grüße, Nora",
  },
  {
    "id": "STIM-LS-A2-001",
    "kind": "listening",
    "title": "Neuer Arzttermin",
    "audioPath": "/placement-audio/v1/stim-ls-a2-001.mp3",
    "maxPlays": 2,
    "transcript": "Guten Tag, hier ist die Praxis am Markt. Frau Dr. Berger ist am Donnerstag leider nicht da. Wir können Ihnen stattdessen am Freitag um elf Uhr einen Termin anbieten. Bitte rufen Sie uns kurz zurück, wenn der Termin nicht passt.",
    "recordingDirection": "Eine ruhige weibliche Stimme, natürliches A2-Tempo, klare Betonung der Änderung und des neuen Termins.",
  },
  {
    "id": "STIM-LS-A2-002",
    "kind": "listening",
    "title": "Wohnungsbesichtigung",
    "audioPath": "/placement-audio/v1/stim-ls-a2-002.mp3",
    "maxPlays": 2,
    "transcript": "Interessentin: Ist die Wohnung noch frei? Vermieter: Ja. Sie hat zwei Zimmer und kostet einschließlich Nebenkosten siebenhundertachtzig Euro. Haustiere sind erlaubt, aber im Haus darf nicht geraucht werden. Besichtigen können Sie sie am Montagabend.",
    "recordingDirection": "Zwei Stimmen, normales A2-Tempo; Zahlen deutlich, aber nicht übertrieben langsam sprechen.",
  },
  {
    "id": "STIM-LS-A2-003",
    "kind": "listening",
    "title": "Führung im Museum",
    "audioPath": "/placement-audio/v1/stim-ls-a2-003.mp3",
    "maxPlays": 2,
    "transcript": "Herzlich willkommen im Stadtmuseum. Die Führung durch die neue Ausstellung beginnt um fünfzehn Uhr im ersten Stock. Sie dauert ungefähr eine Stunde. Große Taschen geben Sie bitte vorher kostenlos an der Garderobe ab.",
    "recordingDirection": "Eine freundliche Stimme über Lautsprecher, gut verständlich, leicht halliger Raum, aber kein störendes Geräusch.",
  },
  {
    "id": "STIM-RD-B1-001",
    "kind": "reading",
    "title": "Neue Projektzeiten",
    "text": "Betreff: Arbeitszeiten im Projekt „Nord“\n\nHallo zusammen, ab nächster Woche können wir unsere Arbeitszeit im Projekt flexibler einteilen. Wichtig ist nur, dass zwischen 10 und 15 Uhr alle erreichbar sind. Die wöchentliche Teamrunde bleibt dienstags um 11 Uhr. Bitte tragt geplante Abwesenheiten spätestens einen Tag vorher in den Kalender ein, damit die Zusammenarbeit funktioniert. Viele Grüße, Lena",
  },
  {
    "id": "STIM-RD-B1-002",
    "kind": "reading",
    "title": "Lesepatinnen und Lesepaten gesucht",
    "text": "Die Stadtbibliothek sucht Freiwillige, die einmal pro Woche mit Grundschulkindern lesen. Eine pädagogische Ausbildung ist nicht nötig. Vor dem ersten Einsatz gibt es eine kostenlose Einführung. Die Treffen finden nachmittags in der Bibliothek statt und dauern jeweils eine Stunde. Interessierte sollten sich mindestens für sechs Monate verpflichten, damit die Kinder eine feste Bezugsperson haben.",
  },
  {
    "id": "STIM-RD-B1-003",
    "kind": "reading",
    "title": "Antwort auf eine Reklamation",
    "text": "Sehr geehrte Frau Martens, vielen Dank für Ihre Nachricht. Es tut uns leid, dass Ihre Bestellung beschädigt angekommen ist. Wir senden Ihnen heute kostenlos einen Ersatz. Das defekte Gerät müssen Sie nicht sofort zurückschicken: In den nächsten Tagen erhalten Sie per E-Mail ein Rücksendeetikett. Wenn der Ersatz ebenfalls beschädigt sein sollte, erstatten wir Ihnen selbstverständlich den Kaufpreis. Freundliche Grüße, Kundenservice Berger",
  },
  {
    "id": "STIM-LS-B1-001",
    "kind": "listening",
    "title": "Besprechung zum Sommerfest",
    "audioPath": "/placement-audio/v1/stim-ls-b1-001.mp3",
    "maxPlays": 2,
    "transcript": "Tarek: Für das Sommerfest würde ich gern eine Band buchen. Miriam: Die Idee gefällt mir, aber dafür reicht unser Budget wahrscheinlich nicht. Wir könnten stattdessen einen DJ fragen und mehr Geld für Essen einplanen. Tarek: Einverstanden. Dann hole ich bis Freitag zwei Angebote ein, und du klärst die Kosten für das Essen.",
    "recordingDirection": "Zwei Stimmen, natürliches B1-Tempo, kooperativer Ton. Den Vorschlag und die Aufgabenverteilung klar markieren.",
  },
  {
    "id": "STIM-LS-B1-002",
    "kind": "listening",
    "title": "Leihfahrräder in der Stadt",
    "audioPath": "/placement-audio/v1/stim-ls-b1-002.mp3",
    "maxPlays": 2,
    "transcript": "Seit Montag stehen in der Innenstadt zweihundert neue Leihfahrräder zur Verfügung. Wer sie nutzen möchte, muss sich zunächst in einer App registrieren. Die ersten dreißig Minuten jeder Fahrt sind kostenlos. Die Stadt hofft, dass dadurch vor allem kurze Autofahrten vermieden werden. Einige Anwohner kritisieren jedoch, dass an manchen Stationen bereits Fahrräder auf den Gehwegen stehen.",
    "recordingDirection": "Eine Radiostimme, normales B1-Tempo. Sachlicher Bericht mit leichtem Kontrast vor „Einige Anwohner“.",
  },
  {
    "id": "STIM-LS-B1-003",
    "kind": "listening",
    "title": "Nachricht wegen Fehlens im Kurs",
    "audioPath": "/placement-audio/v1/stim-ls-b1-003.mp3",
    "maxPlays": 2,
    "transcript": "Hallo Frau Brandt, hier ist Luis Ortega aus dem B1-Kurs. Ich kann morgen leider nicht kommen, weil mein Sohn krank ist. Könnten Sie mir bitte sagen, welche Seiten wir bearbeiten? Die Hausaufgabe kann ich am Donnerstag per E-Mail schicken. Vielen Dank und bis nächste Woche.",
    "recordingDirection": "Eine männliche Stimme, natürliche Mailbox-Nachricht, freundlich und leicht besorgt.",
  },
  {
    "id": "STIM-RD-B1P-001",
    "kind": "reading",
    "title": "Regeln im Coworking-Raum",
    "text": "Der Coworking-Raum soll konzentriertes Arbeiten ermöglichen, gleichzeitig aber auch den Austausch fördern. Telefonate sind deshalb in den markierten Bereichen erlaubt; längere Videokonferenzen gehören in die kleinen Besprechungsräume. Wer einen Raum reserviert, sollte ihn freigeben, sobald er nicht mehr benötigt wird. Die Regeln funktionieren allerdings nur, wenn Verstöße zunächst direkt und respektvoll angesprochen werden.",
  },
  {
    "id": "STIM-RD-B1P-002",
    "kind": "reading",
    "title": "Versuch mit einer Vier-Tage-Woche",
    "text": "Ein mittelständischer Betrieb hat sechs Monate lang eine Vier-Tage-Woche getestet. Die Beschäftigten arbeiteten insgesamt zwei Stunden weniger, sollten ihre Aufgaben aber weiterhin vollständig erledigen. Laut Geschäftsführung blieb die Produktivität stabil, und die Zahl der Krankheitstage sank leicht. Einige Teams berichteten jedoch von größerem Zeitdruck an den verbleibenden Tagen. Der Betrieb will das Modell deshalb nicht unverändert übernehmen, sondern je nach Abteilung anpassen.",
  },
  {
    "id": "STIM-RD-B1P-003",
    "kind": "reading",
    "title": "Vorschlag für eine interne Schulung",
    "text": "Betreff: Prioritäten für die nächste Schulung\n\nAus den Rückmeldungen des Teams ergibt sich ein klares Bild: Eine allgemeine Einführung in die neue Software wäre für die meisten zu oberflächlich. Sinnvoller wäre eine Schulung zu den drei Arbeitsabläufen, bei denen derzeit die meisten Fehler entstehen. Damit auch Teilzeitkräfte teilnehmen können, schlage ich zwei kürzere Termine statt eines ganzen Tages vor. Falls das Budget nur einen Termin erlaubt, sollten wir den Abschnitt zur automatischen Auswertung priorisieren.",
  },
  {
    "id": "STIM-LS-B1P-001",
    "kind": "listening",
    "title": "Diskussion über Erreichbarkeit",
    "audioPath": "/placement-audio/v1/stim-ls-b1p-001.mp3",
    "maxPlays": 2,
    "transcript": "Leitung: Ich schlage vor, dass wir nach 18 Uhr grundsätzlich keine internen Nachrichten mehr erwarten. Kollegin: Das Ziel finde ich richtig. Eine starre Uhrzeit passt aber nicht zu allen Teams, besonders nicht zu denen mit internationalen Partnern. Leitung: Dann könnten die Teams eigene Zeitfenster festlegen, solange klar dokumentiert ist, wann niemand reagieren muss. Kollegin: Damit könnte ich gut leben.",
    "recordingDirection": "Zwei Stimmen, flüssiges starkes B1-Tempo. Die Kollegin stimmt dem Ziel zu, lehnt aber die starre Umsetzung ab.",
  },
  {
    "id": "STIM-LS-B1P-002",
    "kind": "listening",
    "title": "Bilanz eines Stadtgartens",
    "audioPath": "/placement-audio/v1/stim-ls-b1p-002.mp3",
    "maxPlays": 2,
    "transcript": "Der Gemeinschaftsgarten am Weserufer ist vor zwei Jahren mit dem Ziel gestartet, Nachbarschaft und Umweltbildung zu verbinden. Die Zahl der regelmäßigen Teilnehmenden ist geringer als erhofft, doch Schulen nutzen das Gelände inzwischen häufig für Projekte. Die Organisatoren werten das nicht als Scheitern: Das ursprüngliche Angebot habe sich verändert, erfülle aber weiterhin einen wichtigen Zweck. Für das nächste Jahr wünschen sie sich verlässlichere Unterstützung bei der Verwaltung.",
    "recordingDirection": "Eine Radiostimme, natürliches B1+/B2-Tempo, abwägender Ton, klare Betonung des unerwarteten Nutzens.",
  },
  {
    "id": "STIM-LS-B1P-003",
    "kind": "listening",
    "title": "Bitte um schriftliche Bestätigung",
    "audioPath": "/placement-audio/v1/stim-ls-b1p-003.mp3",
    "maxPlays": 2,
    "transcript": "Guten Tag Frau Nguyen, hier ist Daniel Weber von der Personalabteilung. Wir haben Ihren Antrag auf Änderung der Arbeitszeit erhalten. Damit die Änderung ab dem ersten Oktober wirksam werden kann, benötigen wir noch die unterschriebene Vereinbarung. Bitte schicken Sie uns das Dokument spätestens bis Montag. Sollten einzelne Angaben nicht stimmen, melden Sie sich bitte vor der Unterschrift bei mir.",
    "recordingDirection": "Eine männliche Stimme, höflicher formeller Ton, normales Tempo, Frist und Bedingung deutlich.",
  },
  {
    "id": "STIM-RD-B2-001",
    "kind": "reading",
    "title": "Empfehlungsalgorithmen",
    "text": "Digitale Plattformen versprechen, aus einer unüberschaubaren Auswahl genau die passenden Inhalte herauszufiltern. Bequem ist das zweifellos. Problematisch wird es jedoch, wenn Nutzerinnen und Nutzer weder erkennen können, nach welchen Kriterien Empfehlungen entstehen, noch Einfluss auf diese Kriterien haben. Vollständige technische Offenlegung ist kaum realistisch; nachvollziehbare Wahlmöglichkeiten wären dagegen ein erreichbares Ziel. Transparenz bedeutet in diesem Fall also weniger, jeden Rechenschritt zu zeigen, als die entscheidenden Annahmen und Steuerungsmöglichkeiten sichtbar zu machen.",
  },
  {
    "id": "STIM-RD-B2-002",
    "kind": "reading",
    "title": "Hybride Zusammenarbeit",
    "text": "In vielen Unternehmen wird die Debatte über Homeoffice vor allem über die Zahl der Bürotage geführt. Damit wird ein komplexes Problem auf eine leicht messbare Größe reduziert. Für die Zusammenarbeit ist häufig wichtiger, welche Aufgaben persönliche Anwesenheit wirklich erfordern, wie Informationen dokumentiert werden und ob neue Mitarbeitende informelle Kontakte aufbauen können. Ein gut begründeter gemeinsamer Tag kann daher wirkungsvoller sein als drei Anwesenheitstage, an denen jedes Teammitglied allein an Videokonferenzen teilnimmt.",
  },
  {
    "id": "STIM-RD-B2-003",
    "kind": "reading",
    "title": "Ein günstigeres Nahverkehrsticket",
    "text": "Ein deutlich günstigeres Monatsticket kann den öffentlichen Nahverkehr attraktiver machen. Es wäre allerdings verkürzt, den Preis als einziges Hindernis zu betrachten. Wer abends keine Verbindung nach Hause hat oder sich auf verspätete Busse nicht verlassen kann, steigt auch mit einem billigen Ticket nicht dauerhaft um. Preismaßnahmen sollten deshalb mit einem stabileren Angebot verbunden werden. Sonst wächst zwar kurzfristig die Zahl der verkauften Tickets, nicht unbedingt aber die tatsächliche Nutzung.",
  },
  {
    "id": "STIM-LS-B2-001",
    "kind": "listening",
    "title": "Kulturelle Förderung",
    "audioPath": "/placement-audio/v1/stim-ls-b2-001.mp3",
    "maxPlays": 2,
    "transcript": "Moderator: Sollte die Stadt kleinere Kulturprojekte stärker fördern? Expertin: Ja, aber nicht, indem man einfach den vorhandenen Etat auf immer mehr Projekte verteilt. Dann erhält zwar jede Initiative etwas, doch kaum eine kann verlässlich planen. Sinnvoller wären mehrjährige Förderlinien mit klaren Kriterien. Gleichzeitig muss ein Teil des Budgets für neue, noch unerprobte Ideen offenbleiben, sonst stabilisiert man nur das bereits Bekannte.",
    "recordingDirection": "Zwei Stimmen, B2-Tempo, präzise und abwägend. Die Expertin verbindet Zustimmung mit einer Kritik an bloßer Verteilung.",
  },
  {
    "id": "STIM-LS-B2-002",
    "kind": "listening",
    "title": "KI im Unterricht",
    "audioPath": "/placement-audio/v1/stim-ls-b2-002.mp3",
    "maxPlays": 2,
    "transcript": "Lehrerin: Automatische Rückmeldungen können Lernenden helfen, häufiger zu üben. Forscher: Richtig, solange klar ist, worin ihre Grenzen liegen. Ein System erkennt vielleicht typische Grammatikfehler, versteht aber nicht zuverlässig, ob ein Text in einer konkreten Situation angemessen wirkt. Lehrerin: Deshalb sollte es Hinweise liefern, nicht die pädagogische Entscheidung ersetzen.",
    "recordingDirection": "Zwei Stimmen, sachliches B2-Tempo. Gemeinsame Position: nützlich als Unterstützung, nicht als vollständiger Ersatz.",
  },
  {
    "id": "STIM-LS-B2-003",
    "kind": "listening",
    "title": "Reparaturcafé",
    "audioPath": "/placement-audio/v1/stim-ls-b2-003.mp3",
    "maxPlays": 2,
    "transcript": "Im Reparaturcafé werden defekte Alltagsgegenstände gemeinsam untersucht. Eine erfolgreiche Reparatur ist dabei nicht garantiert. Trotzdem betrachten die Ehrenamtlichen auch Termine ohne erfolgreiche Reparatur als sinnvoll: Besucherinnen und Besucher erfahren, warum ein Gerät nicht mehr funktioniert und ob sich eine Reparatur noch lohnt. Der eigentliche Wert liegt daher nicht nur in vermiedenem Müll, sondern auch im weitergegebenen Wissen.",
    "recordingDirection": "Eine Radiostimme, flüssig, erklärend; Kontrast bei „Trotzdem“ und Schlussfolgerung deutlich.",
  },
  {
    "id": "STIM-RD-C1-001",
    "kind": "reading",
    "title": "Wenn Kennzahlen Veränderungen steuern",
    "text": "Kennzahlen gelten häufig als neutrale Abbilder einer Organisation. Tatsächlich verändern sie jedoch, worauf Aufmerksamkeit gerichtet wird. Sobald etwa die Bearbeitungsdauer zum zentralen Qualitätsmaß erklärt wird, optimieren Beschäftigte verständlicherweise ihre Abläufe auf Geschwindigkeit. Ob ein Anliegen damit angemessen gelöst ist, kann aus dem Blick geraten. Das spricht nicht gegen Messung, wohl aber gegen die Vorstellung, eine einzelne Zahl könne Qualität lediglich beschreiben, ohne sie zugleich mitzuformen. Eine verantwortliche Steuerung muss daher auch beobachten, welche Verhaltensanreize ihre Messgrößen erzeugen.",
  },
  {
    "id": "STIM-RD-C1-002",
    "kind": "reading",
    "title": "Beteiligung ohne falsche Erwartungen",
    "text": "Öffentliche Beteiligung wird mitunter an einem unerfüllbaren Maßstab gemessen: Jede geäußerte Präferenz müsse sich unmittelbar in der endgültigen Entscheidung wiederfinden. Doch Beteiligung bedeutet weder Vetorecht für Einzelne noch die Auflösung politischer Verantwortung. Glaubwürdig ist sie dann, wenn Entscheidungsspielräume vorab ehrlich benannt werden, unterschiedliche Argumente nachweisbar in die Abwägung eingehen und begründet wird, weshalb bestimmte Vorschläge übernommen oder verworfen wurden. Enttäuschung lässt sich damit nicht ausschließen; der Eindruck bloßer Inszenierung hingegen schon eher.",
  },
  {
    "id": "STIM-RD-C1-003",
    "kind": "reading",
    "title": "Wissenschaft verständlich kommunizieren",
    "text": "Wissenschaftskommunikation wird oft als Übersetzungsproblem dargestellt: Komplexe Erkenntnisse müssten nur einfacher formuliert werden. Das ist notwendig, greift aber zu kurz. Forschungsergebnisse sind mit Unsicherheiten, methodischen Grenzen und vorläufigen Deutungen verbunden. Werden diese zugunsten einer klaren Botschaft vollständig ausgeblendet, entsteht zwar Verständlichkeit, aber keine verlässliche Orientierung. Die eigentliche Kunst besteht darin, Unsicherheit nicht als Schwäche erscheinen zu lassen, sondern als Bestandteil eines transparenten Erkenntnisprozesses zu vermitteln.",
  },
  {
    "id": "STIM-LS-C1-001",
    "kind": "listening",
    "title": "Expertengespräch zur Wirkung von Verboten",
    "audioPath": "/placement-audio/v1/stim-ls-c1-001.mp3",
    "maxPlays": 2,
    "transcript": "Moderatorin: Sie bezweifeln also, dass ein Verbot wirkt? Experte: Nein, so pauschal würde ich das nicht sagen. Ein Verbot kann Verhalten sehr schnell verändern. Die entscheidende Frage ist, ob damit nur die sichtbare Handlung verschwindet oder auch das zugrunde liegende Problem. Wird beispielsweise eine Nutzung an einem Ort untersagt, kann sie sich schlicht verlagern. Das ist kein Argument gegen Regeln, aber für eine Evaluation, die mehr misst als die unmittelbare Einhaltung.",
    "recordingDirection": "Zwei Stimmen, natürliches C1-Tempo. Der Experte korrigiert die zugespitzte Frage und entwickelt eine differenzierte Position.",
  },
  {
    "id": "STIM-LS-C1-002",
    "kind": "listening",
    "title": "Vorstandssitzung über ein Pilotprojekt",
    "audioPath": "/placement-audio/v1/stim-ls-c1-002.mp3",
    "maxPlays": 2,
    "transcript": "Vorsitzende: Die Ergebnisse rechtfertigen aus meiner Sicht eine sofortige Ausweitung. Finanzleiter: Sie rechtfertigen eine Fortsetzung, aber noch keine flächendeckende Einführung. Wir haben positive Rückmeldungen, allerdings nur aus zwei freiwillig teilnehmenden Abteilungen. Vorsitzende: Dann verlängern wir den Versuch und nehmen zwei Abteilungen mit anderen Arbeitsabläufen hinzu. Finanzleiter: Damit ließe sich prüfen, ob der Effekt am Modell liegt oder daran, dass bisher nur besonders motivierte Abteilungen teilgenommen haben.",
    "recordingDirection": "Zwei professionelle Stimmen, zügiges C1-Tempo. Deutlicher Unterschied zwischen Ausweitung und methodisch verbesserter Fortsetzung.",
  },
  {
    "id": "STIM-LS-C1-003",
    "kind": "listening",
    "title": "Vortrag über institutionelles Lernen",
    "audioPath": "/placement-audio/v1/stim-ls-c1-003.mp3",
    "maxPlays": 2,
    "transcript": "Organisationen sprechen gern davon, aus Fehlern zu lernen. Häufig folgt auf einen Vorfall jedoch vor allem eine neue Regel. Das kann notwendig sein, ersetzt aber keine Analyse der Bedingungen, unter denen der Fehler plausibel wurde. Wer ausschließlich nach individuellem Versagen sucht, erhält eine klare Verantwortungszuschreibung, aber wenig Wissen darüber, weshalb ähnliche Entscheidungen auch anderen Personen hätten passieren können. Institutionelles Lernen beginnt daher dort, wo Erklärung nicht mit Entschuldigung verwechselt wird.",
    "recordingDirection": "Eine Stimme, präzises C1-Tempo, vortragsartig, sachlich; Schlusskontrast deutlich betonen.",
  },
  {
    "id": "STIM-RD-BA1A2-LOW-001",
    "kind": "reading",
    "title": "Kursinformation",
    "text": "Hallo zusammen, der Kurs fällt heute aus. Wir treffen uns wieder am Montag um 18 Uhr. Bitte macht bis dahin die Aufgaben auf Seite 42. Viele Grüße, Frau Klein",
  },
  {
    "id": "STIM-LS-BA1A2-LOW-001",
    "kind": "listening",
    "title": "Geänderter Termin",
    "audioPath": "/placement-audio/v1/stim-ls-ba1a2-low-001.mp3",
    "maxPlays": 2,
    "transcript": "Hallo Herr Saleh, Ihr Termin morgen ist nicht um neun Uhr, sondern um halb elf. Bitte kommen Sie zehn Minuten früher.",
    "recordingDirection": "Eine Stimme, langsam und deutlich, Änderung und Bitte klar betonen.",
  },
  {
    "id": "STIM-RD-BA1A2-UP-001",
    "kind": "reading",
    "title": "Ausflug am Sonntag",
    "text": "Hallo Amira, am Sonntag möchten wir am See picknicken. Wir treffen uns um 11 Uhr am Bahnhof und fahren zusammen mit dem Bus. Bitte bring etwas zu trinken mit. Wenn es stark regnet, gehen wir stattdessen ins Stadtmuseum. Liebe Grüße, Jana",
  },
  {
    "id": "STIM-LS-BA1A2-UP-001",
    "kind": "listening",
    "title": "Ansage am Bahnhof",
    "audioPath": "/placement-audio/v1/stim-ls-ba1a2-up-001.mp3",
    "maxPlays": 2,
    "transcript": "Achtung am Gleis drei. Der Zug nach Oldenburg fährt heute etwa zwanzig Minuten später. Reisende nach Delmenhorst können auch die S-Bahn um 14 Uhr 12 von Gleis eins nehmen.",
    "recordingDirection": "Bahnhofsansage, verständlich, leichtes Raumgefühl, Zahlen deutlich.",
  },
  {
    "id": "STIM-RD-BA2B1-LOW-001",
    "kind": "reading",
    "title": "Sportkurs verschoben",
    "text": "Liebe Teilnehmerinnen und Teilnehmer, wegen einer Reparatur in der Turnhalle beginnt der Sportkurs diese Woche erst um 19 Uhr. Der Eingang an der Parkstraße ist geschlossen; bitte benutzen Sie den Eingang hinter dem Gebäude. Ab nächster Woche gelten wieder die normalen Zeiten.",
  },
  {
    "id": "STIM-LS-BA2B1-LOW-001",
    "kind": "listening",
    "title": "Plan für den Abend",
    "audioPath": "/placement-audio/v1/stim-ls-ba2b1-low-001.mp3",
    "maxPlays": 2,
    "transcript": "Nora: Gehen wir heute ins Kino? Sami: Gern, aber der Film um acht ist ausverkauft. Es gibt noch Karten für die Vorstellung um halb zehn. Nora: Das ist mir zu spät. Dann essen wir lieber etwas und gehen am Samstag ins Kino.",
    "recordingDirection": "Zwei Stimmen, natürliches A2-Tempo, Entscheidung am Ende deutlich.",
  },
  {
    "id": "STIM-RD-BA2B1-UP-001",
    "kind": "reading",
    "title": "Neue Regel für Urlaubsanträge",
    "text": "Ab Januar sollen Urlaubsanträge nicht mehr per E-Mail, sondern über das Personalportal gestellt werden. Dadurch können Vertretungen früher geplant und Überschneidungen schneller erkannt werden. Wer keinen Zugang zum Portal hat, wendet sich bitte an die Personalabteilung. Bereits genehmigte Anträge müssen nicht erneut eingegeben werden.",
  },
  {
    "id": "STIM-LS-BA2B1-UP-001",
    "kind": "listening",
    "title": "Information zur Baustelle",
    "audioPath": "/placement-audio/v1/stim-ls-ba2b1-up-001.mp3",
    "maxPlays": 2,
    "transcript": "Die Bauarbeiten an der Brücke dauern voraussichtlich zwei Wochen länger als geplant. Grund dafür sind Schäden, die erst nach Beginn der Arbeiten sichtbar wurden. Für Autos bleibt die Umleitung bestehen. Busse dürfen ab Montag wieder über die Brücke fahren, allerdings nur auf einer Spur, sodass es weiterhin zu Verspätungen kommen kann.",
    "recordingDirection": "Eine Radiostimme, normales B1-Tempo, Ursache und eingeschränkte Verbesserung klar.",
  },
  {
    "id": "STIM-RD-B1B1P-LOW-001",
    "kind": "reading",
    "title": "Interne Fortbildung",
    "text": "Für die Fortbildung am 12. Mai sind noch fünf Plätze frei. Sie richtet sich an Beschäftigte, die regelmäßig Kundengespräche führen. Die Abteilung übernimmt die Teilnahmegebühr, wenn die Anmeldung bis Ende April erfolgt. Wer teilnehmen möchte, stimmt den Termin bitte vorher mit der Teamleitung ab.",
  },
  {
    "id": "STIM-LS-B1B1P-LOW-001",
    "kind": "listening",
    "title": "Abstimmung über einen Termin",
    "audioPath": "/placement-audio/v1/stim-ls-b1b1p-low-001.mp3",
    "maxPlays": 2,
    "transcript": "Lea: Ich könnte die Präsentation am Donnerstag fertigstellen. Karim: Dann bleibt kaum Zeit für Rückmeldungen. Schaffst du einen ersten Entwurf bis Dienstag? Lea: Ja, wenn du mir die aktuellen Zahlen heute noch schickst. Karim: Abgemacht, ich sende sie dir bis 16 Uhr.",
    "recordingDirection": "Zwei Stimmen, normales B1-Tempo, Bedingung und Vereinbarung deutlich.",
  },
  {
    "id": "STIM-RD-B1B1P-UP-001",
    "kind": "reading",
    "title": "Rückmeldung zu neuen Besprechungen",
    "text": "Die kürzeren Besprechungen werden im Team überwiegend positiv bewertet. Allerdings sparen sie nur dann Zeit, wenn Entscheidungen und offene Aufgaben anschließend schriftlich festgehalten werden. In den letzten Wochen war häufig unklar, wer einen Punkt weiterverfolgt. Statt die Termine wieder zu verlängern, sollte deshalb zunächst die Dokumentation verbindlicher werden.",
  },
  {
    "id": "STIM-LS-B1B1P-UP-001",
    "kind": "listening",
    "title": "Bewertung einer neuen Software",
    "audioPath": "/placement-audio/v1/stim-ls-b1b1p-up-001.mp3",
    "maxPlays": 2,
    "transcript": "Moderator: Hat die neue Software Ihre Arbeit erleichtert? Mitarbeiterin: Bei Standardfällen eindeutig. Wir sparen dort mehrere Schritte. Sobald ein Vorgang aber von der üblichen Reihenfolge abweicht, wird es komplizierter als früher. Deshalb würde ich nicht sagen, dass die Software schlecht ist; sie wurde nur zu stark auf den Normalfall zugeschnitten.",
    "recordingDirection": "Zwei Stimmen, B1+/B2-Tempo, differenzierte Bewertung statt pauschalem Urteil.",
  },
  {
    "id": "STIM-RD-B1PB2-LOW-001",
    "kind": "reading",
    "title": "Testphase für neue Öffnungszeiten",
    "text": "Die Bibliothek hat ihre Öffnungszeiten drei Monate lang bis 21 Uhr verlängert. Besonders in der Prüfungszeit wurde das Angebot gut genutzt. An gewöhnlichen Wochentagen kamen nach 19 Uhr dagegen nur wenige Besucherinnen und Besucher. Statt die längeren Zeiten ganz abzuschaffen, plant die Bibliothek nun, sie auf bestimmte Monate und Veranstaltungen zu beschränken.",
  },
  {
    "id": "STIM-LS-B1PB2-LOW-001",
    "kind": "listening",
    "title": "Rückblick auf eine Veranstaltung",
    "audioPath": "/placement-audio/v1/stim-ls-b1pb2-low-001.mp3",
    "maxPlays": 2,
    "transcript": "Sofia: Insgesamt war der Informationstag gut besucht, aber am Nachmittag waren viele Beratungsstände leer. Jan: Vielleicht war das Programm zu lang. Sofia: Möglich. Die kurzen Vorträge waren dagegen fast immer voll. Beim nächsten Mal könnten wir weniger Themen anbieten und mehr Zeit für Fragen lassen. Jan: Das wäre aus meiner Sicht sinnvoller, als den Tag einfach zu verlängern.",
    "recordingDirection": "Zwei Stimmen, B1+/B2-Tempo, reflektierend. Empfehlung am Ende klar, aber nicht überbetont.",
  },
  {
    "id": "STIM-RD-B1PB2-UP-001",
    "kind": "reading",
    "title": "Warum eine einfache Regel nicht genügt",
    "text": "Die Forderung, alle internen Informationen grundsätzlich zu teilen, klingt zunächst transparent. In der Praxis kann eine unstrukturierte Informationsmenge jedoch denselben Effekt haben wie fehlende Information: Relevantes bleibt unentdeckt. Transparenz setzt deshalb nicht bloß Zugang voraus, sondern auch nachvollziehbare Zuständigkeiten, verständliche Zusammenfassungen und die Möglichkeit, Entscheidungen bis zu ihren Grundlagen zurückzuverfolgen.",
  },
  {
    "id": "STIM-LS-B1PB2-UP-001",
    "kind": "listening",
    "title": "Bewertung kostenloser Angebote",
    "audioPath": "/placement-audio/v1/stim-ls-b1pb2-up-001.mp3",
    "maxPlays": 2,
    "transcript": "Moderatorin: Wenn ein Angebot kostenlos ist, erreicht es doch automatisch mehr Menschen. Forscherin: Die finanzielle Hürde fällt weg, das stimmt. Aber Zeit, Entfernung oder Unsicherheit darüber, ob man willkommen ist, können ebenso entscheidend sein. Kostenlosigkeit ist daher weder bedeutungslos noch ausreichend. Wer Teilhabe erhöhen will, muss prüfen, welche Barrieren für die jeweilige Zielgruppe tatsächlich bestehen.",
    "recordingDirection": "Zwei Stimmen, flüssiges B2-Tempo. Forscherin nimmt die Prämisse teilweise an und begrenzt sie dann.",
  },
  {
    "id": "STIM-RD-B2C1-LOW-001",
    "kind": "reading",
    "title": "Öffentliche Daten und Vertrauen",
    "text": "Die Veröffentlichung öffentlicher Daten kann Vertrauen stärken, sofern die Informationen verständlich und aktuell sind. Eine unkommentierte Tabelle erfüllt zwar formal die Forderung nach Offenheit, hilft vielen Bürgerinnen und Bürgern aber kaum bei der Einordnung. Behörden sollten daher nicht weniger Daten bereitstellen, sondern zusätzlich erklären, welche Fragen die Zahlen beantworten können und welche nicht.",
  },
  {
    "id": "STIM-LS-B2C1-LOW-001",
    "kind": "listening",
    "title": "Stadtzentrum ohne Autos",
    "audioPath": "/placement-audio/v1/stim-ls-b2c1-low-001.mp3",
    "maxPlays": 2,
    "transcript": "Planerin: Ein autofreier Bereich kann die Aufenthaltsqualität deutlich erhöhen. Händler: Das kann stimmen, aber wir wissen noch zu wenig darüber, wie Lieferungen erfolgen und wie Menschen mit eingeschränkter Mobilität das Zentrum erreichen können. Planerin: Deshalb sollte die Stadt zunächst an Wochenenden testen und die Auswirkungen messen. Händler: Mit einem begrenzten Versuch und klaren Ausnahmen könnte ich mich eher anfreunden.",
    "recordingDirection": "Zwei Stimmen, B2-Tempo, sachliche Annäherung und bedingte Zustimmung.",
  },
  {
    "id": "STIM-RD-B2C1-UP-001",
    "kind": "reading",
    "title": "Der Reiz eindeutiger Erklärungen",
    "text": "Eindeutige Erklärungen besitzen gerade in unübersichtlichen Situationen eine große Anziehungskraft. Sie reduzieren Komplexität und weisen Verantwortung klar zu. Ihr Vorteil für die Orientierung kann jedoch zum erkenntnistheoretischen Nachteil werden, wenn widersprüchliche Befunde nur noch als Störung erscheinen. Eine tragfähige Erklärung muss nicht jede Unsicherheit beseitigen; sie sollte vielmehr angeben, welche Beobachtungen sie gut erfasst, wo ihre Reichweite endet und welche konkurrierenden Deutungen weiterhin plausibel sind.",
  },
  {
    "id": "STIM-LS-B2C1-UP-001",
    "kind": "listening",
    "title": "Kommentar zur Fehlerkultur",
    "audioPath": "/placement-audio/v1/stim-ls-b2c1-up-001.mp3",
    "maxPlays": 2,
    "transcript": "Der Appell, Fehler offen anzusprechen, bleibt folgenlos, solange Offenheit individuell riskant ist. Wer Nachteile befürchten muss, wird auch in einer freundlich formulierten Kulturkampagne schweigen. Umgekehrt erzeugt die bloße Abschaffung von Sanktionen noch keine lernende Organisation. Erforderlich sind Verfahren, die zwischen vertretbaren Fehlentscheidungen, systematischen Problemen und bewusstem Fehlverhalten unterscheiden. Erst diese Differenzierung macht Offenheit zugleich möglich und verantwortlich.",
    "recordingDirection": "Eine Stimme, C1-Tempo, argumentativ dicht. Kontraste und abschließende Synthese präzise sprechen.",
  },
] as const;
