import type { ContentLocale, CourseNarrative } from '@/lib/content/types';

export const courseNarrativesByLocale: Record<ContentLocale, CourseNarrative[]> = {
  en: [
    {
      slug: 'intensive-german',
      locale: 'en',
      audience: 'For anyone who wants to work intensively on their German, for their studies, their job and everyday life.',
      promise: 'Build your German step by step, with regular practice and a group to learn alongside.',
      outcomes: ['Progress through the language levels', 'Improved speaking confidence', 'A steady learning routine'],
      teachingStyle: ['Communicative tasks', 'Small-group correction', 'Weekly progress checkpoints'],
    },
    {
      slug: 'evening-german',
      locale: 'en',
      audience: 'Working professionals and trainees balancing work with language learning.',
      promise: 'Learn German after work and use what you’ve learnt in everyday life straight away.',
      outcomes: ['Improved workplace communication', 'Vocabulary for daily life', 'Progress over the long term'],
      teachingStyle: ['Real-life scenarios', 'Focused grammar blocks', 'Peer conversation practice'],
    },
    {
      slug: 'special-courses',
      locale: 'en',
      audience: 'For anyone who wants to work on specific language skills.',
      promise: 'Deepen your knowledge of grammar, write better or speak more freely. You choose the focus.',
      outcomes: ['More confidence in your chosen skill', 'Practice geared to your own goals and to everyday life', 'A focus on the areas you want to improve'],
      teachingStyle: ['Workshop format', 'Time for practice and individual feedback', 'Learning by doing'],
    },
    {
      slug: 'medical-german',
      locale: 'en',
      audience: 'For doctors and healthcare professionals preparing their German for work in Germany.',
      promise: 'Practise patient consultations, medical reports and conversations with colleagues as you prepare for clinical work and the Fachsprachprüfung.',
      outcomes: [
        'Confident patient history-taking (Anamnese)',
        'Speaking appropriately to patients and colleagues, and writing professional documentation',
        'Structured case presentations (Fallvorstellungen)',
        'Precise medical report writing (Arztbriefe)',
        'Preparation for the medical language exam (FSP)',
      ],
      teachingStyle: [
        'Role-play clinical consultations with instructor feedback',
        'Case-based language drills (real hospital scenarios)',
        'Interdisciplinary communication practice',
        'Pronunciation coaching for medical terminology',
      ],
    },
    {
      slug: 'bildungszeit',
      locale: 'en',
      audience: 'Employees on Bildungszeit with clear learning goals.',
      promise: 'Use your Bildungszeit, Bremen’s paid leave for further training, to focus on German and English. We’ll advise you on the right course and the paperwork you need.',
      outcomes: ['Focused time for learning', 'More language practice', 'Advice on how to continue learning'],
      teachingStyle: ['Compact intensive blocks', 'Applied communication tasks', 'Goal-based lesson plans'],
    },
    {
      slug: 'in-company',
      locale: 'en',
      audience: 'Teams that need German for internal and client communication.',
      promise: 'Job-focused language training, built around real work. Courses tailored to your company and your team’s day-to-day needs.',
      outcomes: [
        'A curriculum built around your company, for confident communication at work',
        'A clearer understanding of instructions and assignments',
        'More confidence when communicating in your team',
      ],
      teachingStyle: ['Needs analysis', 'Industry vocabulary tracks', 'Location and format agreed with your company'],
    },
    {
      slug: 'exam-preparation',
      locale: 'en',
      audience: 'Learners preparing for telc Deutsch B2 or telc Deutsch C1 Hochschule.',
      promise: 'Get to know the tasks, practise under exam conditions and learn from personal feedback.',
      outcomes: ['Familiarity with the exam tasks', 'Time management under pressure', 'More confidence on exam day'],
      teachingStyle: ['Practice exams', 'Learning from your mistakes', 'Task-by-task coaching'],
    },
    {
      slug: 'german-for-groups',
      locale: 'en',
      audience: 'School classes, universities and organisations bringing a group to Bremen.',
      audienceInPromise: true,
      promise: 'Learn German and experience Bremen together: we plan the lessons, the culture programme and the accommodation around your group. The programme is for school classes, universities and organisations coming to Bremen as a group, and every participant receives a certificate of attendance.',
      outcomes: [
        'Lesson content shaped around your group and its goals',
        'German practised outside the classroom every day',
        'Experiencing local culture with Bremen host families',
      ],
      teachingStyle: [
        '20 lessons a week',
        'Speaking-led sessions using content you choose',
        'Culture programme and excursions built into the week',
      ],
    },
  ],
  de: [
    {
      slug: 'intensive-german',
      locale: 'de',
      audience: 'Für alle, die sich intensiv mit Deutsch beschäftigen möchten – für das Studium, den Beruf und den Alltag.',
      promise: 'Schritt für Schritt sicherer auf Deutsch: mit regelmäßiger Übung und einer Gruppe, die gemeinsam lernt.',
      outcomes: ['Fortschritte auf deinem Sprachniveau', 'Mehr Sprechsicherheit', 'Verlässlicher Lernrhythmus'],
      teachingStyle: ['Kommunikative Aufgaben', 'Korrektur in Kleingruppen', 'Wöchentliche Lernchecks'],
    },
    {
      slug: 'evening-german',
      locale: 'de',
      audience: 'Berufstätige und Auszubildende mit begrenzter Zeit am Tag.',
      promise: 'Nach Feierabend Deutsch lernen und das Gelernte gleich im Alltag anwenden.',
      outcomes: ['Sicherere Kommunikation im Beruf', 'Mehr Alltagsvokabular', 'Langfristiger Fortschritt'],
      teachingStyle: ['Praxisnahe Szenarien', 'Gezielte Grammatikblöcke', 'Partnerarbeit'],
    },
    {
      slug: 'special-courses',
      locale: 'de',
      audience: 'Für alle, die gezielt an speziellen Sprachfertigkeiten arbeiten möchten.',
      promise: 'Grammatik vertiefen, besser schreiben oder freier sprechen: Wähle deinen Schwerpunkt.',
      outcomes: ['Mehr Sicherheit im gewählten Bereich', 'Übungen für die individuellen Lernziele und den Alltag', 'Individuelle Schwerpunkte'],
      teachingStyle: ['Workshop-Format', 'Intensives Feedback', 'Lernen durch Anwenden'],
    },
    {
      slug: 'medical-german',
      locale: 'de',
      audience: 'Für Ärztinnen, Ärzte und medizinische Fachkräfte, die sich sprachlich auf die Arbeit in Deutschland vorbereiten.',
      promise: 'Übe Patientengespräche, Arztbriefe und den Austausch im Team – mit Blick auf den Klinikalltag und die Fachsprachprüfung.',
      outcomes: [
        'Sichere Anamnesegespräche auf Deutsch',
        'Adressatengerechte mündliche Kommunikation und berufsspezifische schriftliche Dokumentation',
        'Strukturierte Fallvorstellungen im Team',
        'Präzises Verfassen von Arztbriefen',
        'Gezielte Vorbereitung auf die Fachsprachprüfung (FSP)',
      ],
      teachingStyle: [
        'Rollenspiele mit echten Kliniksituationen',
        'Fallbasierte Spracharbeit mit direktem Feedback',
        'Interdisziplinäre Kommunikationsübungen',
        'Aussprachetraining für medizinische Fachbegriffe',
      ],
    },
    {
      slug: 'bildungszeit',
      locale: 'de',
      audience: 'Berufstätige in der Bildungszeit mit klaren Lernzielen.',
      promise: 'Nutze deine Bildungszeit, um dich auf Deutsch und Englisch zu konzentrieren. Wir beraten dich zum Kurs und zu den benötigten Unterlagen.',
      outcomes: ['Konzentrierte Zeit zum Lernen', 'Mehr Sprachpraxis', 'Beratung zum Weiterlernen'],
      teachingStyle: ['Kompakte Intensivblöcke', 'Alltagsnahe Kommunikation', 'Zielorientierte Planung'],
    },
    {
      slug: 'in-company',
      locale: 'de',
      audience: 'Teams, die Deutsch direkt im Arbeitsalltag brauchen.',
      promise: 'Fachbezogenes Sprachtraining mit direktem Praxisbezug. Passgenaue und bedarfsgerechte Angebote für den Arbeitsalltag in Ihrer Firma.',
      outcomes: [
        'Speziell auf Ihre Firma zugeschnittenes Curriculum für sichere Kommunikation in der beruflichen Praxis',
        'Besseres Verständnis bei Arbeitsanweisungen und -aufträgen',
        'Sicheres Auftreten in der Teamkommunikation',
      ],
      teachingStyle: ['Bedarfsanalyse', 'Branchenvokabular', 'Ort und Unterrichtsform nach Vereinbarung'],
    },
    {
      slug: 'exam-preparation',
      locale: 'de',
      audience: 'Lernende mit Ziel telc Deutsch B2 oder telc Deutsch C1 Hochschule.',
      promise: 'Lerne die Aufgaben kennen, übe unter Prüfungsbedingungen und erhalte persönliches Feedback.',
      outcomes: ['Sichere Aufgabenstrategie', 'Besseres Zeitmanagement', 'Mehr Prüfungsruhe'],
      teachingStyle: ['Übungsprüfungen', 'Auswertung und Besprechung deiner Fehler', 'Gezielte Unterstützung bei einzelnen Aufgaben'],
    },
    {
      slug: 'german-for-groups',
      locale: 'de',
      audience: 'Schulklassen, Hochschulen und Organisationen, die mit einer Gruppe nach Bremen kommen.',
      audienceInPromise: true,
      promise: 'Deutsch lernen und Bremen gemeinsam erleben: Wir planen den Unterricht, das Kulturprogramm und die Unterkunft passend zu Ihrer Gruppe. Dieses Programm ist für Schulklassen, Hochschulen und Organisationen, die mit einer Gruppe nach Bremen kommen möchten. Alle Teilnehmenden erhalten eine Teilnahmebescheinigung.',
      outcomes: [
        'Unterrichtsinhalte passend zu Ihrer Gruppe und ihren Zielen',
        'Täglich Deutsch auch außerhalb des Unterrichts',
        'Kultur vor Ort in Bremer Gastfamilien kennenlernen',
      ],
      teachingStyle: [
        '20 Unterrichtsstunden pro Woche',
        'Sprechorientierter Unterricht mit Inhalten Ihrer Wahl',
        'Kulturprogramm und Ausflüge fest im Wochenplan',
      ],
    },
  ],
};
