import type { ContentLocale, CourseNarrative } from '@/lib/content/types';

export const courseNarrativesByLocale: Record<ContentLocale, CourseNarrative[]> = {
  en: [
    {
      slug: 'intensive-german',
      locale: 'en',
      audience: 'For learners who want to make German a central part of their week, for study, work or everyday life.',
      promise: 'Build your German step by step, with regular practice and a group to learn alongside.',
      outcomes: ['Progress through the language levels', 'Improved speaking confidence', 'A steady learning routine'],
      teachingStyle: ['Communicative tasks', 'Small-group correction', 'Weekly progress checkpoints'],
    },
    {
      slug: 'evening-german',
      locale: 'en',
      audience: 'Working professionals and trainees balancing work with language learning.',
      promise: 'Steady progress after work hours without losing structure.',
      outcomes: ['Improved workplace communication', 'Vocabulary for daily life', 'Flexible long-term progression'],
      teachingStyle: ['Real-life scenarios', 'Focused grammar blocks', 'Peer conversation practice'],
    },
    {
      slug: 'special-courses',
      locale: 'en',
      audience: 'For learners who want more practice in a particular area of German.',
      promise: 'Work on grammar, writing or speaking in a course with a clear focus.',
      outcomes: ['More confidence in your chosen skill', 'Practice you can use in class and daily life', 'A focus on the areas you want to improve'],
      teachingStyle: ['Workshop format', 'Time for practice and individual feedback', 'Learning by doing'],
    },
    {
      slug: 'medical-german',
      locale: 'en',
      audience: 'Doctors and healthcare professionals preparing for clinical work and licensing in Germany.',
      promise: 'Practise patient consultations, medical reports and conversations with colleagues as you prepare for clinical work and the Fachsprachprüfung.',
      outcomes: [
        'Confident patient history-taking (Anamnese)',
        'Clear physical examination language',
        'Structured case presentations (Fallvorstellungen)',
        'Precise medical report writing (Arztbriefe)',
        'Preparation for the medical language exam (FSP)',
      ],
      teachingStyle: [
        'Role-play clinical consultations with instructor feedback',
        'Case-based language drills (real hospital scenarios)',
        'Interdisciplinary communication practice',
        'Pronunciation coaching for medical terminology',
      ],
    },
    {
      slug: 'bildungszeit',
      locale: 'en',
      audience: 'Employees using educational leave for intensive German training.',
      promise: 'Use your educational leave to focus on German. We can advise you on the course and the documents you need.',
      outcomes: ['Focused time for learning', 'Practical speaking gains', 'Advice on how to continue learning'],
      teachingStyle: ['Compact intensive blocks', 'Applied communication tasks', 'Goal-based lesson plans'],
    },
    {
      slug: 'in-company',
      locale: 'en',
      audience: 'Teams that need German for internal and client communication.',
      promise: 'Company-specific language training linked directly to work tasks.',
      outcomes: ['More confidence in meetings', 'Clearer emails', 'Better understanding within your team'],
      teachingStyle: ['Needs analysis', 'Industry vocabulary tracks', 'Location and format agreed with your company'],
    },
    {
      slug: 'exam-preparation',
      locale: 'en',
      audience: 'Learners preparing for telc Deutsch B2 or telc Deutsch C1 Hochschule.',
      promise: 'Get to know the tasks, practise under exam conditions and learn from personal feedback.',
      outcomes: ['Familiarity with the exam tasks', 'Time management under pressure', 'More confidence on exam day'],
      teachingStyle: ['Practice exams', 'Learning from your mistakes', 'Task-by-task coaching'],
    },
    {
      slug: 'german-for-groups',
      locale: 'en',
      audience: 'School classes, universities, and organisations bringing a group to Bremen.',
      promise: 'A German programme built around your group, combined with a Bremen culture programme and host-family accommodation.',
      outcomes: [
        'Lesson content shaped around your group and its goals',
        'German practised outside the classroom every day',
        'A participation certificate for every learner',
      ],
      teachingStyle: [
        '20 hours of lessons per week',
        'Speaking-led sessions using content you choose',
        'Culture programme and excursions built into the week',
      ],
    },
  ],
  de: [
    {
      slug: 'intensive-german',
      locale: 'de',
      audience: 'Für alle, die sich intensiv mit Deutsch beschäftigen möchten – für Studium, Beruf oder Alltag.',
      promise: 'Schritt für Schritt sicherer auf Deutsch: mit regelmäßiger Übung und einer Gruppe, die gemeinsam lernt.',
      outcomes: ['Fortschritte auf Ihrem Sprachniveau', 'Mehr Sprechsicherheit', 'Verlässlicher Lernrhythmus'],
      teachingStyle: ['Kommunikative Aufgaben', 'Korrektur in Kleingruppen', 'Wöchentliche Lernchecks'],
    },
    {
      slug: 'evening-german',
      locale: 'de',
      audience: 'Berufstätige und Auszubildende mit begrenzter Zeit am Tag.',
      promise: 'Nach Feierabend Deutsch lernen und das Gelernte gleich im Alltag anwenden.',
      outcomes: ['Sicherere Kommunikation im Beruf', 'Mehr Alltagsvokabular', 'Langfristiger Fortschritt'],
      teachingStyle: ['Praxisnahe Szenarien', 'Gezielte Grammatikblöcke', 'Partnerarbeit'],
    },
    {
      slug: 'special-courses',
      locale: 'de',
      audience: 'Für alle, die gezielt an einem Bereich ihres Deutschs arbeiten möchten.',
      promise: 'Grammatik vertiefen, besser schreiben oder freier sprechen: Wählen Sie Ihren Schwerpunkt.',
      outcomes: ['Mehr Sicherheit im gewählten Bereich', 'Übung für Unterricht und Alltag', 'Individuelle Schwerpunkte'],
      teachingStyle: ['Workshop-Format', 'Intensives Feedback', 'Lernen durch Anwenden'],
    },
    {
      slug: 'medical-german',
      locale: 'de',
      audience: 'Für Ärztinnen, Ärzte und medizinische Fachkräfte, die sich sprachlich auf die Arbeit in Deutschland vorbereiten.',
      promise: 'Üben Sie Patientengespräche, Arztbriefe und den Austausch im Team – mit Blick auf den Klinikalltag und die Fachsprachprüfung.',
      outcomes: [
        'Sichere Anamnesegespräche auf Deutsch',
        'Klare Sprache bei der körperlichen Untersuchung',
        'Strukturierte Fallvorstellungen im Team',
        'Präzises Verfassen von Arztbriefen',
        'Gezielte Vorbereitung auf die Fachsprachprüfung (FSP)',
      ],
      teachingStyle: [
        'Rollenspiele mit echten Kliniksituationen',
        'Fallbasierte Spracharbeit mit direktem Feedback',
        'Interdisziplinäre Kommunikationsübungen',
        'Aussprachetraining für medizinische Fachbegriffe',
      ],
    },
    {
      slug: 'bildungszeit',
      locale: 'de',
      audience: 'Berufstätige in der Bildungszeit mit klaren Lernzielen.',
      promise: 'Nutzen Sie Ihre Bildungszeit, um sich auf Deutsch zu konzentrieren. Wir beraten Sie zum Kurs und den benötigten Unterlagen.',
      outcomes: ['Konzentrierte Zeit zum Lernen', 'Mehr Sprechpraxis', 'Beratung zum Weiterlernen'],
      teachingStyle: ['Kompakte Intensivblöcke', 'Alltagsnahe Kommunikation', 'Zielorientierte Planung'],
    },
    {
      slug: 'in-company',
      locale: 'de',
      audience: 'Teams, die Deutsch direkt im Arbeitsalltag brauchen.',
      promise: 'Firmenbezogenes Sprachtraining mit direktem Praxisbezug.',
      outcomes: ['Sicherere Meetings', 'Bessere E-Mail-Kommunikation', 'Bessere Verständigung im Team'],
      teachingStyle: ['Bedarfsanalyse', 'Branchenvokabular', 'Ort und Unterrichtsform nach Vereinbarung'],
    },
    {
      slug: 'exam-preparation',
      locale: 'de',
      audience: 'Lernende mit Ziel telc Deutsch B2 oder telc Deutsch C1 Hochschule.',
      promise: 'Lernen Sie die Aufgaben kennen, üben Sie unter Prüfungsbedingungen und erhalten Sie persönliches Feedback.',
      outcomes: ['Sichere Aufgabenstrategie', 'Besseres Zeitmanagement', 'Mehr Prüfungsruhe'],
      teachingStyle: ['Übungsprüfungen', 'Auswertung und Besprechung Ihrer Fehler', 'Gezielte Unterstützung bei einzelnen Aufgaben'],
    },
    {
      slug: 'german-for-groups',
      locale: 'de',
      audience: 'Schulklassen, Hochschulen und Organisationen, die mit einer Gruppe nach Bremen kommen.',
      promise: 'Deutsch lernen und Bremen gemeinsam erleben: Wir planen Unterricht, Kulturprogramm und Unterkunft passend zu Ihrer Gruppe.',
      outcomes: [
        'Unterrichtsinhalte passend zu Ihrer Gruppe und ihren Zielen',
        'Täglich Deutsch auch außerhalb des Unterrichts',
        'Teilnahmebescheinigung für alle Teilnehmenden',
      ],
      teachingStyle: [
        '20 Unterrichtsstunden pro Woche',
        'Sprechorientierter Unterricht mit Inhalten Ihrer Wahl',
        'Kulturprogramm und Ausflüge fest im Wochenplan',
      ],
    },
  ],
};
