import { proofMetricsByLocale } from '@/config/content/proof-metrics';
import { socialProofByLocale } from '@/config/content/social-proof';
import { resolveHeroMedia } from '@/config/content/media-library';
import type {
  ContentLocale,
  HeroArchetype,
  HeroCta,
  HeroPageKey,
  HeroSpec,
  HeroThemeKey,
  HeroVariant,
} from '@/lib/content/types';

type HeroSeed = {
  pageKey: HeroPageKey;
  variant: HeroVariant;
  archetype: HeroArchetype;
  themeKey: HeroThemeKey;
  eyebrow: string;
  headline: string;
  subheadline: string;
  ctas: HeroCta[];
  chips?: string[];
  visualKey: Parameters<typeof resolveHeroMedia>[0];
  metricCount?: number;
  storyIndex?: number;
};

function pageMetrics(locale: ContentLocale, size = 4) {
  return proofMetricsByLocale[locale].slice(0, size);
}

function pageStory(locale: ContentLocale, index = 0) {
  const item = socialProofByLocale[locale][index] ?? socialProofByLocale[locale][0];

  return {
    quote: item.quote,
    personDisplay: item.personDisplay,
    country: item.country,
    roleLabel: locale === 'de' ? 'Lernstimme' : 'Student voice',
    sourcePlatform: item.sourcePlatform,
    sourceUrl: item.sourceUrl,
    verificationStatus: item.verificationStatus,
  };
}

function toRecord(locale: ContentLocale, seeds: HeroSeed[]): Record<HeroPageKey, HeroSpec> {
  return seeds.reduce<Record<HeroPageKey, HeroSpec>>((acc, seed) => {
    acc[seed.pageKey] = {
      pageKey: seed.pageKey,
      locale,
      variant: seed.variant,
      archetype: seed.archetype,
      themeKey: seed.themeKey,
      eyebrow: seed.eyebrow,
      headline: seed.headline,
      subheadline: seed.subheadline,
      ctas: seed.ctas,
      proofMetrics: pageMetrics(locale, seed.metricCount ?? 4),
      story: pageStory(locale, seed.storyIndex ?? 0),
      chips: seed.chips,
      visual: {
        kind: 'image',
        src: resolveHeroMedia(seed.visualKey),
        alt: seed.headline,
      },
    };

    return acc;
  }, {} as Record<HeroPageKey, HeroSpec>);
}

const enSeeds: HeroSeed[] = [
  {
    pageKey: 'home',
    variant: 'immersive',
    archetype: 'A',
    themeKey: 'home',
    eyebrow: 'CASA Bremen',
    headline: 'Learn German. Feel at home.',
    subheadline:
      'Learn with people from around the world, with personal support as you settle into life in Bremen.',
    ctas: [
      { label: 'Find my course', href: '/courses', kind: 'primary' },
      { label: 'Get advice', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Bremen', 'International community', 'telc exams', 'Culture and excursions'],
    visualKey: 'home',
    metricCount: 4,
    storyIndex: 0,
  },
  {
    pageKey: 'about',
    variant: 'immersive',
    archetype: 'F',
    themeKey: 'about',
    eyebrow: 'Our school',
    headline: 'A place to learn and settle in',
    subheadline:
      'Since 1983, people from around the world have come to CASA to learn German and make connections in Bremen.',
    ctas: [
      { label: 'Get advice', href: '/contact', kind: 'primary' },
      { label: 'Find the right course', href: '/courses', kind: 'secondary' },
    ],
    chips: ['Since 1983', '30,000+ learners', 'International community'],
    visualKey: 'about',
    metricCount: 4,
    storyIndex: 1,
  },
  {
    pageKey: 'courses',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'courses',
    eyebrow: 'Courses',
    headline: 'Find your German course',
    subheadline:
      'Choose a course that suits your level, your plans and your everyday life. We are here to help if you are unsure.',
    ctas: [
      { label: 'Register for a course', href: '/registration/course', kind: 'primary' },
      { label: 'Check your German level', href: '/placement-test', kind: 'secondary' },
    ],
    chips: ['A1–C1', 'Morning and evening', 'For visa applicants'],
    visualKey: 'courses',
    metricCount: 3,
    storyIndex: 2,
  },
  {
    pageKey: 'course-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'courses',
    eyebrow: 'Course information',
    headline: 'German for your next step',
    subheadline:
      'Find out what you’ll learn, how the course works and how to join. If you have any questions, we’re here to help.',
    ctas: [
      { label: 'Ask about this course', href: '/registration/course', kind: 'primary' },
      { label: 'Get advice', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Practical learning', 'Feedback from teachers', 'Speaking practice'],
    visualKey: 'course-detail',
    metricCount: 3,
    storyIndex: 0,
  },
  {
    pageKey: 'exams',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'exams',
    eyebrow: 'Exams',
    headline: 'Your telc exam at CASA',
    subheadline:
      'Find out all about telc Deutsch B2 and telc Deutsch C1 Hochschule, our preparation courses, the exam dates and how to register.',
    ctas: [
      { label: 'See the dates', href: '#exam-sessions', kind: 'primary' },
      { label: 'Register for an exam', href: '/registration/exam', kind: 'secondary' },
    ],
    chips: ['telc exam centre', 'B2 preparation', 'C1 Hochschule'],
    visualKey: 'exams',
    metricCount: 3,
    storyIndex: 2,
  },
  {
    pageKey: 'exam-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'exams',
    eyebrow: 'Exam information',
    headline: 'Everything you need to know before exam day',
    subheadline:
      'Here you’ll find the dates, the requirements and the documents you need, so you arrive at the exam well prepared.',
    ctas: [
      { label: 'Register for an exam', href: '/registration/exam', kind: 'primary' },
      { label: 'Get exam advice', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Registration', 'Preparation', 'The exam', 'Results'],
    visualKey: 'exam-detail',
    metricCount: 3,
    storyIndex: 1,
  },
  {
    pageKey: 'accommodation',
    variant: 'structured',
    archetype: 'D',
    themeKey: 'accommodation',
    eyebrow: 'Accommodation',
    headline: 'A place to call home in Bremen',
    subheadline:
      'During your intensive course, you can live in a CASA shared flat or with hosts in Bremen. Here we introduce both options.',
    ctas: [
      { label: 'Ask about accommodation', href: '/contact?topic=accommodation', kind: 'primary' },
      { label: 'Ask about a course and accommodation', href: '/registration/course', kind: 'secondary' },
    ],
    chips: ['Shared flats', 'Host families', 'Safe and supported'],
    visualKey: 'accommodation',
    metricCount: 3,
    storyIndex: 0,
  },
  {
    pageKey: 'accommodation-detail',
    variant: 'structured',
    archetype: 'D',
    themeKey: 'accommodation',
    eyebrow: 'Accommodation details',
    headline: 'A home that suits you',
    subheadline: 'Get to know the accommodation and see what it costs. Write and tell us what you’re looking for.',
    ctas: [
      { label: 'Ask about accommodation', href: '/contact?topic=accommodation', kind: 'primary' },
      { label: 'Get advice', href: '/contact', kind: 'secondary' },
    ],
    chips: ['How you’ll live', 'Safety', 'Clear steps'],
    visualKey: 'accommodation-detail',
    metricCount: 3,
    storyIndex: 1,
  },
  {
    pageKey: 'contact',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Contact',
    headline: 'Talk to the CASA team',
    subheadline: 'Tell us what is on your mind. We take time to listen and help you work out your next step.',
    ctas: [{ label: 'Ask for a CASA plan', href: '/contact', kind: 'primary' }],
    visualKey: 'contact',
    metricCount: 2,
  },
  {
    pageKey: 'faq',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'FAQ',
    headline: 'Answers to the most important questions before you start',
    subheadline: 'Here you’ll find answers about courses, exams, registration and life in Bremen.',
    ctas: [{ label: 'Contact the office', href: '/contact', kind: 'primary' }],
    visualKey: 'faq',
    metricCount: 2,
  },
  {
    pageKey: 'news',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'default',
    eyebrow: 'News',
    headline: 'Stories from our classes and from Bremen',
    subheadline: 'Read news, experiences and practical tips from our school.',
    ctas: [
      { label: 'Read the news', href: '/news', kind: 'primary' },
      { label: 'Find the right course', href: '/courses', kind: 'secondary' },
    ],
    chips: ['From our classes', 'Exams', 'Community'],
    visualKey: 'news',
    metricCount: 3,
  },
  {
    pageKey: 'news-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'default',
    eyebrow: 'Article',
    headline: 'News and stories from CASA',
    subheadline: 'A closer look at learning and life at our international language school.',
    ctas: [
      { label: 'Find the right course', href: '/courses', kind: 'primary' },
      { label: 'Get advice', href: '/contact', kind: 'secondary' },
    ],
    visualKey: 'news-detail',
    metricCount: 2,
  },
  {
    pageKey: 'placement-test',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Placement',
    headline: 'Find the right place to start',
    subheadline: 'With the placement test, we can recommend a course that builds on what you already know.',
    ctas: [{ label: 'Ask about placement', href: '/contact?topic=placement', kind: 'primary' }],
    visualKey: 'placement-test',
    metricCount: 2,
  },
  {
    pageKey: 'registration-course',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'courses',
    eyebrow: 'Course registration',
    headline: 'Register for your German course',
    subheadline: 'Tell us which course you’d like to join and fill in your details. We’ll check your registration and then get in touch with the next steps.',
    ctas: [{ label: 'Complete registration', href: '/registration/course', kind: 'primary' }],
    visualKey: 'registration-course',
    metricCount: 2,
  },
  {
    pageKey: 'registration-exam',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'exams',
    eyebrow: 'Exam registration',
    headline: 'Register for your telc exam',
    subheadline: 'Choose your exam and date and fill in your details. Please keep an eye on the registration deadline.',
    ctas: [{ label: 'Complete registration', href: '/registration/exam', kind: 'primary' }],
    visualKey: 'registration-exam',
    metricCount: 2,
  },
  {
    pageKey: 'imprint',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Legal',
    headline: 'Imprint',
    subheadline: 'Provider details and legal disclosure for CASA Internationale Sprachschule Bremen.',
    ctas: [{ label: 'Contact office', href: '/contact', kind: 'primary' }],
    visualKey: 'imprint',
    metricCount: 2,
  },
  {
    pageKey: 'privacy',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Legal',
    headline: 'Privacy Policy',
    subheadline: 'How CASA handles personal data for website visitors, applicants, and learners.',
    ctas: [{ label: 'Contact office', href: '/contact', kind: 'primary' }],
    visualKey: 'privacy',
    metricCount: 2,
  },
  {
    pageKey: 'terms',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Legal',
    headline: 'Terms & Conditions',
    subheadline: 'Core contractual terms for courses, exams, and related CASA services.',
    ctas: [{ label: 'Contact office', href: '/contact', kind: 'primary' }],
    visualKey: 'terms',
    metricCount: 2,
  },
];

const deSeeds: HeroSeed[] = [
  {
    pageKey: 'home',
    variant: 'immersive',
    archetype: 'A',
    themeKey: 'home',
    eyebrow: 'CASA Bremen',
    headline: 'Deutsch lernen. In Bremen ankommen.',
    subheadline:
      'Lerne Deutsch mit Menschen aus aller Welt und einem Team, das sich Zeit für dich nimmt.',
    ctas: [
      { label: 'Meinen Kurs finden', href: '/courses', kind: 'primary' },
      { label: 'Beratung anfragen', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Bremen', 'Community', 'Prüfungswege', 'Kulturprogramme'],
    visualKey: 'home',
    metricCount: 4,
    storyIndex: 0,
  },
  {
    pageKey: 'about',
    variant: 'immersive',
    archetype: 'F',
    themeKey: 'about',
    eyebrow: 'Unsere Schule',
    headline: 'Ein Ort zum Lernen und Ankommen',
    subheadline:
      'Seit 1983 kommen bei CASA Menschen aus aller Welt zusammen, um Deutsch zu lernen und in Bremen Anschluss zu finden.',
    ctas: [
      { label: 'Beratung anfragen', href: '/contact', kind: 'primary' },
      { label: 'Passenden Kurs finden', href: '/courses', kind: 'secondary' },
    ],
    chips: ['Seit 1983', '30.000+ Lernende', 'Internationale Gemeinschaft'],
    visualKey: 'about',
    metricCount: 4,
    storyIndex: 1,
  },
  {
    pageKey: 'courses',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'courses',
    eyebrow: 'Kurse',
    headline: 'Finde deinen Deutschkurs',
    subheadline:
      'Wähle einen Kurs, der zu deinen Vorkenntnissen, deinen Plänen und deinem Alltag passt. Wir beraten dich gern.',
    ctas: [
      { label: 'Zur Kursanmeldung', href: '/registration/course', kind: 'primary' },
      { label: 'Einstufung starten', href: '/placement-test', kind: 'secondary' },
    ],
    chips: ['A1–C1', 'Morgens und abends', 'Visa-orientiert'],
    visualKey: 'courses',
    metricCount: 3,
    storyIndex: 2,
  },
  {
    pageKey: 'course-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'courses',
    eyebrow: 'Kursinformationen',
    headline: 'Deutsch für deinen nächsten Schritt',
    subheadline:
      'Hier erfährst du, was du lernst, wie der Kurs abläuft und wie du teilnehmen kannst. Bei Fragen sind wir für dich da.',
    ctas: [
      { label: 'Kurs anfragen', href: '/registration/course', kind: 'primary' },
      { label: 'Beratung anfragen', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Praxisnah', 'Rückmeldung von Lehrkräften', 'Sprechpraxis'],
    visualKey: 'course-detail',
    metricCount: 3,
  },
  {
    pageKey: 'exams',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'exams',
    eyebrow: 'Prüfungen',
    headline: 'Deine telc-Prüfung bei CASA',
    subheadline:
      'Hier erfährst du alles über telc Deutsch B2 und telc Deutsch C1 Hochschule, über unsere Vorbereitungskurse, die Prüfungstermine und die Anmeldung.',
    ctas: [
      { label: 'Termine ansehen', href: '#exam-sessions', kind: 'primary' },
      { label: 'Zur Prüfungsanmeldung', href: '/registration/exam', kind: 'secondary' },
    ],
    chips: ['telc-Prüfungszentrum', 'Vorbereitung auf B2', 'C1 Hochschule'],
    visualKey: 'exams',
    metricCount: 3,
  },
  {
    pageKey: 'exam-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'exams',
    eyebrow: 'Prüfungsinformationen',
    headline: 'Alles Wichtige vor dem Prüfungstag',
    subheadline: 'Hier findest du die Termine, die Voraussetzungen und die Unterlagen, die du brauchst. So kommst du gut vorbereitet zur Prüfung.',
    ctas: [
      { label: 'Zur Prüfungsanmeldung', href: '/registration/exam', kind: 'primary' },
      { label: 'Prüfungsberatung anfragen', href: '/contact', kind: 'secondary' },
    ],
    chips: ['Anmeldung', 'Vorbereitung', 'Prüfung', 'Ergebnis'],
    visualKey: 'exam-detail',
    metricCount: 3,
  },
  {
    pageKey: 'accommodation',
    variant: 'structured',
    archetype: 'D',
    themeKey: 'accommodation',
    eyebrow: 'Unterkunft',
    headline: 'Ein Zuhause für deine Zeit in Bremen',
    subheadline: 'Während deines Intensivkurses kannst du in einer CASA-WG oder bei Bremer Gastgebern wohnen. Hier stellen wir dir beide Möglichkeiten vor.',
    ctas: [
      { label: 'Unterkunft anfragen', href: '/contact?topic=accommodation', kind: 'primary' },
      { label: 'Kurs und Unterkunft anfragen', href: '/registration/course', kind: 'secondary' },
    ],
    chips: ['WGs', 'Gastfamilien', 'Sicher begleitet'],
    visualKey: 'accommodation',
    metricCount: 3,
  },
  {
    pageKey: 'accommodation-detail',
    variant: 'structured',
    archetype: 'D',
    themeKey: 'accommodation',
    eyebrow: 'Unterkunftsdetails',
    headline: 'Wohnen, wie es zu dir passt',
    subheadline: 'Hier lernst du die Unterkunft kennen und siehst, was sie kostet. Schreib uns, was du dir wünschst.',
    ctas: [
      { label: 'Unterkunft anfragen', href: '/contact?topic=accommodation', kind: 'primary' },
      { label: 'Beratung anfragen', href: '/contact', kind: 'secondary' },
    ],
    chips: ['So wohnst du', 'Sicherheit', 'Klare Abläufe'],
    visualKey: 'accommodation-detail',
    metricCount: 3,
  },
  {
    pageKey: 'contact',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Kontakt',
    headline: 'Mit dem CASA-Team sprechen',
    subheadline: 'Erzähl uns, was dich beschäftigt. Wir hören zu und überlegen gemeinsam mit dir, wie es weitergehen kann.',
    ctas: [{ label: 'CASA-Plan anfragen', href: '/contact', kind: 'primary' }],
    visualKey: 'contact',
    metricCount: 2,
  },
  {
    pageKey: 'faq',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'FAQ',
    headline: 'Antworten auf die wichtigsten Fragen vor dem Start',
    subheadline: 'Hier findest du Antworten rund um Kurse, Prüfungen, die Anmeldung und das Leben in Bremen.',
    ctas: [{ label: 'Büro kontaktieren', href: '/contact', kind: 'primary' }],
    visualKey: 'faq',
    metricCount: 2,
  },
  {
    pageKey: 'news',
    variant: 'structured',
    archetype: 'B',
    themeKey: 'default',
    eyebrow: 'Aktuelles',
    headline: 'Geschichten aus dem Unterricht und aus Bremen',
    subheadline: 'Hier liest du Neuigkeiten, Erfahrungen und praktische Tipps aus unserer Schule.',
    ctas: [
      { label: 'Zu den Neuigkeiten', href: '/news', kind: 'primary' },
      { label: 'Passenden Kurs finden', href: '/courses', kind: 'secondary' },
    ],
    chips: ['Aus dem Unterricht', 'Prüfungen', 'Gemeinschaft'],
    visualKey: 'news',
    metricCount: 3,
  },
  {
    pageKey: 'news-detail',
    variant: 'structured',
    archetype: 'E',
    themeKey: 'default',
    eyebrow: 'Artikel',
    headline: 'Neuigkeiten und Geschichten von CASA',
    subheadline: 'Einblicke in das Lernen und Leben an unserer internationalen Sprachschule.',
    ctas: [
      { label: 'Passenden Kurs finden', href: '/courses', kind: 'primary' },
      { label: 'Beratung anfragen', href: '/contact', kind: 'secondary' },
    ],
    visualKey: 'news-detail',
    metricCount: 2,
  },
  {
    pageKey: 'placement-test',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Einstufung',
    headline: 'Finde den passenden Einstieg',
    subheadline: 'Mit dem Einstufungstest können wir dir einen Kurs empfehlen, der an deine bisherigen Kenntnisse anknüpft.',
    ctas: [{ label: 'Einstufung anfragen', href: '/contact?topic=placement', kind: 'primary' }],
    visualKey: 'placement-test',
    metricCount: 2,
  },
  {
    pageKey: 'registration-course',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'courses',
    eyebrow: 'Kursanmeldung',
    headline: 'Melde dich zu deinem Deutschkurs an',
    subheadline: 'Schreib uns, welchen Kurs du besuchen möchtest, und gib deine Daten an. Wir prüfen deine Anmeldung und melden uns dann mit den nächsten Schritten bei dir.',
    ctas: [{ label: 'Anmeldung abschließen', href: '/registration/course', kind: 'primary' }],
    visualKey: 'registration-course',
    metricCount: 2,
  },
  {
    pageKey: 'registration-exam',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'exams',
    eyebrow: 'Prüfungsanmeldung',
    headline: 'Melde dich zu deiner telc-Prüfung an',
    subheadline: 'Wähle Prüfung und Termin und trag deine Daten ein. Bitte achte auf die Anmeldefrist.',
    ctas: [{ label: 'Anmeldung abschließen', href: '/registration/exam', kind: 'primary' }],
    visualKey: 'registration-exam',
    metricCount: 2,
  },
  {
    pageKey: 'imprint',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Rechtliches',
    headline: 'Impressum',
    subheadline: 'Anbieterkennzeichnung und rechtliche Hinweise der CASA Internationale Sprachschule Bremen.',
    ctas: [{ label: 'Kontakt aufnehmen', href: '/contact', kind: 'primary' }],
    visualKey: 'imprint',
    metricCount: 2,
  },
  {
    pageKey: 'privacy',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Rechtliches',
    headline: 'Datenschutz',
    subheadline: 'Informationen zur Verarbeitung personenbezogener Daten bei CASA.',
    ctas: [{ label: 'Kontakt aufnehmen', href: '/contact', kind: 'primary' }],
    visualKey: 'privacy',
    metricCount: 2,
  },
  {
    pageKey: 'terms',
    variant: 'utility',
    archetype: 'C',
    themeKey: 'default',
    eyebrow: 'Rechtliches',
    headline: 'AGB',
    subheadline: 'Vertragliche Grundlagen für Kurse, Prüfungen und weitere CASA-Leistungen.',
    ctas: [{ label: 'Kontakt aufnehmen', href: '/contact', kind: 'primary' }],
    visualKey: 'terms',
    metricCount: 2,
  },
];

export const heroSpecsByLocale: Record<ContentLocale, Record<HeroPageKey, HeroSpec>> = {
  en: toRecord('en', enSeeds),
  de: toRecord('de', deSeeds),
};
