/**
 * THE PHOTO NUMBER REGISTRY.
 *
 * While the site runs on colour placeholders, every photograph slot shows a
 * number. That number is how a replacement photograph is identified: you see
 * "24" on the page, you name the new file `24.jpg`, and it lands in the one
 * place the site expects it.
 *
 * ---------------------------------------------------------------------------
 * TWO RULES. BOTH MATTER.
 *
 *   1. NUMBERS ARE PERMANENT. Once a number is in this list it keeps its value
 *      forever. Someone is naming files against these, and renumbering would
 *      silently point their `24.jpg` at a different photograph.
 *
 *   2. ADD BY APPENDING. New photographs go on the END of the list with the
 *      next free number, even when they belong to a group higher up. The
 *      grouping below is how the list was FIRST laid out, not an invariant to
 *      maintain — resorting it to keep the groups tidy would break rule 1.
 * ---------------------------------------------------------------------------
 *
 * Keyed by `src` path rather than by call site, deliberately. A photograph
 * used on the homepage, the course index and a detail page is ONE photograph
 * and gets ONE number, so one delivered file fills all three slots. This is
 * the same reasoning that gives a photograph a stable placeholder colour in
 * `casa-image.tsx`.
 *
 * `ready` is the per-photograph switch back to the real image. Set it to true
 * when a genuine photograph is in place at `src`, and that slot renders the
 * photograph while every other slot stays a numbered placeholder. That is what
 * makes the swap incremental — there is no all-or-nothing flag day. (The
 * master switch in `casa-image.tsx` still turns placeholders off entirely.)
 *
 * `subject` is what the photograph needs to SHOW, written for whoever is
 * choosing or shooting it. It is not alt text — alt text lives at the call
 * site and travels with it.
 *
 * `subject` deliberately describes the PHOTOGRAPH and not the page it lands on.
 * Which page a photograph leads is decided by `public-page-config.ts` and can
 * change without the photograph changing, so a "leads the homepage" note here
 * would go stale silently. Verified per-number usage lives in
 * `docs/MEDIA_PHOTO_NUMBERS.md`, which is generated by crawling the running
 * site rather than read off the config.
 *
 * NOT IN THIS LIST, on purpose:
 *   - Logos and accreditation marks (`proof-band.tsx`, `partner-strip.tsx`).
 *     Those are claims, not decoration, and were never placeholdered.
 *   - The two NewsFlash photographs. They are real, verified images that
 *     already bypass the placeholder wrapper via `next/image` directly.
 *   - Klett textbook covers (`klett-textbooks.ts`). Licensing is unresolved,
 *     so `coverSrc` is unset and no slot renders at all today.
 *
 * `src/config/content/__tests__/photo-numbers.test.ts` fails the build if a
 * photograph is referenced anywhere in `src/` without a number here, if two
 * entries share a number or path, if the numbers stop being contiguous, or if
 * an entry points at a file that is not in `public/`.
 */

export type PhotoSlot = {
  /** Permanent. The name of the replacement file is `${n}.jpg`. */
  n: number;
  /** Canonical path the photograph is served from. */
  src: string;
  /** What the photograph must show, for whoever sources it. */
  subject: string;
  /** True once a real photograph is in place at `src`. */
  ready: boolean;
};

export const photoSlots: PhotoSlot[] = [
  // ---- Community and conversation -----------------------------------------
  {
    n: 1,
    src: '/media/casa/classroom-community-table.jpg',
    subject:
      'Learners around a table mid-conversation, warm and unposed. Needs to survive a wide crop, so leave air at the sides.',
    ready: false,
  },
  {
    n: 2,
    src: '/media/casa/learner-conversation-smile.jpg',
    subject:
      'One learner talking, caught genuinely smiling rather than posing. Reused very widely, so it must not be tied to one course or season.',
    ready: false,
  },
  {
    n: 3,
    src: '/media/casa/school-entrance-sign.jpg',
    subject: 'The CASA entrance with its signage legible — the arrival shot.',
    ready: false,
  },

  // ---- Teaching and classroom ---------------------------------------------
  { n: 4, src: '/media/casa/course-classroom-wide.jpg', subject: 'Wide classroom in session, whole room visible.', ready: false },
  { n: 5, src: '/media/casa/course-classroom-circle.jpg', subject: 'Class seated in a circle — discussion format, no front of room.', ready: false },
  { n: 6, src: '/media/casa/course-discussion-row.jpg', subject: 'A row of learners in discussion, shot along the row.', ready: false },
  { n: 7, src: '/media/casa/course-seminar-wide.jpg', subject: 'Seminar-style room, wide, adult learners at tables.', ready: false },
  { n: 8, src: '/media/casa/course-whiteboard-practice.jpg', subject: 'A learner at the whiteboard working through something, teacher nearby.', ready: false },
  { n: 9, src: '/media/casa/classroom-pair-study.jpg', subject: 'Two learners working as a pair, heads together over one task.', ready: false },
  { n: 10, src: '/media/casa/classroom-map-vocabulary.jpg', subject: 'Vocabulary work against a map — language tied to place.', ready: false },
  { n: 11, src: '/media/casa/learners-writing-class.jpg', subject: 'Learners writing by hand in class, close on the work.', ready: false },
  { n: 12, src: '/media/casa/group-classroom-teacher-activity.jpg', subject: 'Teacher running an activity with the group. This is the widest-travelling photograph on the site, including the homepage hero — it needs to read at full-bleed hero size and in a small card.', ready: false },
  { n: 13, src: '/media/casa/individual-tutoring.jpg', subject: 'One-to-one tutoring, teacher and single learner side by side.', ready: false },
  { n: 14, src: '/media/casa/whiteboard-german-coaching.jpg', subject: 'Coaching at the whiteboard, German visibly on the board.', ready: false },
  { n: 15, src: '/media/casa/business-german-group.jpg', subject: 'Professional adults in a workplace-German setting — business dress, meeting-room feel.', ready: false },
  { n: 16, src: '/media/casa/junior-classroom-listening.jpg', subject: 'Younger learners listening — the junior/teen cohort.', ready: false },
  { n: 17, src: '/media/casa/advising-session-classroom.jpg', subject: 'An advising conversation across a desk — two people, one clearly helping the other.', ready: false },
  { n: 18, src: '/media/casa/exam-preparation-writing.jpg', subject: 'Exam-condition writing — quiet, focused, papers out.', ready: false },
  { n: 19, src: '/media/casa/study-materials-map.jpg', subject: 'Study materials laid out with a map.', ready: false },

  // ---- Groups, excursions, Bremen -----------------------------------------
  { n: 20, src: '/media/casa/group-course-bremen-musicians.jpg', subject: 'Group at the Bremen Town Musicians statue.', ready: false },
  { n: 21, src: '/media/casa/group-course-lunch-table.jpg', subject: 'Group eating together, social rather than instructional.', ready: false },
  { n: 22, src: '/media/casa/group-course-phone-task.jpg', subject: 'Learners on a phone-based task out in the city.', ready: false },
  { n: 23, src: '/media/casa/group-course-walking-bremen.jpg', subject: 'Group walking through Bremen together, city legible behind them.', ready: false },
  { n: 24, src: '/media/casa/student-group-activity-outdoor.jpg', subject: 'Outdoor group activity, daylight, clearly not a classroom.', ready: false },
  { n: 25, src: '/media/casa/bremen-schnoor-houses.jpg', subject: 'The Schnoor quarter houses — Bremen as a place to live, no people needed.', ready: false },

  // ---- Accommodation -------------------------------------------------------
  { n: 26, src: '/media/casa/student-room-balcony.jpg', subject: 'Student room with a balcony, tidy and lit.', ready: false },
  { n: 27, src: '/media/casa/host-family-room.jpg', subject: 'A host family living room — domestic, lived-in.', ready: false },
  { n: 28, src: '/media/casa/shared-flat-kitchen-table.jpg', subject: 'Shared-flat kitchen table, signs of shared use.', ready: false },
  { n: 29, src: '/media/casa/student-shared-kitchen.jpg', subject: 'A shared kitchen in use.', ready: false },
  { n: 30, src: '/media/casa/student-room-alternative-1.jpg', subject: 'A second, different student room — read alongside 26, so vary the layout.', ready: false },

  /*
   * ---- Team portraits ----------------------------------------------------
   * These six are the ones that CANNOT ship. CLAUDE.md hard rule 3: the files
   * currently at these paths are SYNTHETIC placeholders standing in for layout
   * only, and must be replaced with verified portraits of real staff before
   * launch. They must never be presented as real staff in the meantime.
   *
   * Same frame for all six, or the grid will read as six different sittings:
   * head-and-shoulders, consistent eyeline, square crop, plain background.
   */
  { n: 31, src: '/media/casa/team/team-anna-keller-portrait.jpg', subject: 'Staff portrait — Anna Keller. Square, head and shoulders, plain ground. Also used as the teacher-spotlight face on every course page, so it must work at 74px.', ready: false },
  { n: 32, src: '/media/casa/team/team-david-stein-portrait.jpg', subject: 'Staff portrait — David Stein. Match the framing of 31.', ready: false },
  { n: 33, src: '/media/casa/team/team-kareem-yilmaz-portrait.jpg', subject: 'Staff portrait — Kareem Yilmaz. Match the framing of 31.', ready: false },
  { n: 34, src: '/media/casa/team/team-lucas-brandt-portrait.jpg', subject: 'Staff portrait — Lucas Brandt. Match the framing of 31.', ready: false },
  { n: 35, src: '/media/casa/team/team-melanie-hoffmann-portrait.jpg', subject: 'Staff portrait — Melanie Hoffmann. Match the framing of 31.', ready: false },
  { n: 36, src: '/media/casa/team/team-sofia-martin-portrait.jpg', subject: 'Staff portrait — Sofia Martin. Match the framing of 31.', ready: false },

  // ---- Append new photographs below this line, next number, never resort --
];

const slotsBySrc = new Map(photoSlots.map((slot) => [slot.src, slot]));

/** The slot for a photograph path, or undefined if it has no number yet. */
export function photoSlotFor(src: string): PhotoSlot | undefined {
  return slotsBySrc.get(src);
}
