import type { Meaning } from '@/config/brand/meaning';

/**
 * THE PHOTO NUMBER REGISTRY.
 *
 * Every photograph slot has a number. That number is how a replacement
 * photograph is identified: a slot without a photograph renders a calm stand-in
 * panel carrying `data-casa-placeholder="24"`, you name the new file `24.jpg`,
 * and it lands in the one place the site expects it. (Until 2026-10-01 the
 * number was printed on a gradient on the page itself.)
 *
 * ---------------------------------------------------------------------------
 * TWO RULES. BOTH MATTER.
 *
 *   1. NUMBERS ARE PERMANENT. Once a number is in this list it keeps its value
 *      forever. Someone is naming files against these, and renumbering would
 *      silently point their `24.jpg` at a different photograph.
 *
 *   2. ADD BY APPENDING. New photographs go on the END of the list with the
 *      next free number, even when they belong to a group higher up. The
 *      grouping below is how the list was FIRST laid out, not an invariant to
 *      maintain — resorting it to keep the groups tidy would break rule 1.
 * ---------------------------------------------------------------------------
 *
 * Keyed by `src` path rather than by call site, deliberately. A photograph
 * used on the homepage, the course index and a detail page is ONE photograph
 * and gets ONE number, so one delivered file fills all three slots. This is
 * the same reasoning that gives a photograph a stable placeholder colour in
 * `casa-image.tsx`.
 *
 * `ready` is the per-photograph switch back to the real image. Set it to true
 * when a genuine photograph is in place at `src`, and that slot renders the
 * photograph while every other slot stays a numbered placeholder. That is what
 * makes the swap incremental — there is no all-or-nothing flag day. (The
 * master switch in `casa-image.tsx` still turns placeholders off entirely.)
 *
 * `subject` is what the photograph needs to SHOW, written for whoever is
 * choosing or shooting it. It is not alt text — alt text lives at the call
 * site and travels with it.
 *
 * `subject` deliberately describes the PHOTOGRAPH and not the page it lands on.
 * Which page a photograph leads is decided by `public-page-config.ts` and can
 * change without the photograph changing, so a "leads the homepage" note here
 * would go stale silently. Verified per-number usage lives in
 * `docs/MEDIA_PHOTO_NUMBERS.md`, which is generated by crawling the running
 * site rather than read off the config.
 *
 * THE OLD LIBRARY IS GONE (2026-09-10). Every `ready: false` path below is a
 * delivery target with no file behind it — as slot 37 always was. The June
 * derivatives that sat at these paths were removed once the product owner chose
 * the new pool (now archived outside the project; see `docs/MEDIA_LIBRARY.md`)
 * over them; only slots 20
 * and 23 keep a file, in the pool's editorial grade.
 *
 * NOT IN THIS LIST, on purpose:
 *   - Logos and accreditation marks (`proof-band.tsx`).
 *     Those are claims, not decoration, and were never placeholdered.
 *   - NewsFlash photographs. Real, verified images rendered through
 *     `next/image` directly (none in the October 2026 issue).
 *   - Klett textbook covers (`klett-textbooks.ts`). Licensing is unresolved,
 *     so `coverSrc` is unset and no slot renders at all today.
 *
 * `src/config/content/__tests__/photo-numbers.test.ts` fails the build if a
 * photograph is referenced anywhere in `src/` without a number here, if two
 * entries share a number or path, if the numbers stop being contiguous, or if
 * an entry points at a file that is not in `public/`.
 */

export type PhotoSlot = {
  /** Permanent. The name of the replacement file is `${n}.jpg`. */
  n: number;
  /** Canonical path the photograph is served from. */
  src: string;
  /** What the photograph must show, for whoever sources it. */
  subject: string;
  /** True once a real photograph is in place at `src`. */
  ready: boolean;
  /**
   * Where the photograph sits in a box of another shape: Tailwind
   * object-position classes, per breakpoint (crop pass, 2026-10-02). Every
   * box is `object-cover`, so a 4:3 photo in a wide box loses its top and
   * bottom; these keep every head, with a little room above the hair, inside
   * all the boxes the photo is shown in at that width. Computed by
   * scripts/media/fit_positions.py from a crawl of the site; CasaImage applies
   * them unless the call site sets its own position. Literal strings, so
   * Tailwind sees them.
   */
  position?: string;
};

export const photoSlots: PhotoSlot[] = [
  // ---- Community and conversation -----------------------------------------
  {
    n: 1,
    src: '/media/casa/classroom-community-table.jpg',
    subject:
      'Learners around a table mid-conversation, warm and unposed. Needs to survive a wide crop, so leave air at the sides.',
    ready: false,
  },
  {
    n: 2,
    src: '/media/casa/learner-conversation-smile.jpg',
    subject:
      'One learner talking, caught genuinely smiling rather than posing. Reused very widely, so it must not be tied to one course or season.',
    ready: false,
  },
  {
    n: 3,
    src: '/media/casa/school-entrance-sign.jpg',
    subject: 'The CASA entrance with its signage legible — the arrival shot.',
    ready: false,
  },

  // ---- Teaching and classroom ---------------------------------------------
  { n: 4, src: '/media/casa/course-intensive-class.webp', subject: 'Deutsch intensiv. Five learners along the table by the window, following the lesson. Collection frame 060, 4:3 crop with light correction only (scripts/media/build_reel.py), 2026-10-01.', ready: true },
  { n: 5, src: '/media/casa/course-evening-table.webp', subject: 'Abendkurs. Three learners laughing over a shared exercise at the course table. Collection frame 088, 4:3 crop with light correction only (scripts/media/build_reel.py), 2026-10-01.', ready: true },
  { n: 6, src: '/media/casa/course-discussion-row.jpg', subject: 'A row of learners in discussion, shot along the row.', ready: false },
  { n: 7, src: '/media/casa/course-seminar-wide.jpg', subject: 'Seminar-style room, wide, adult learners at tables.', ready: false },
  { n: 8, src: '/media/casa/course-special-smartboard.webp', subject: 'Spezialkurse. The teacher speaking at the smart board, her class working in front of her. Collection frame 067, 4:3 crop, modern grade (scripts/media/build_reel.py), 2026-10-02.', ready: true },
  { n: 9, src: '/media/casa/classroom-pair-study.jpg', subject: 'Two learners working as a pair, heads together over one task.', ready: false },
  { n: 10, src: '/media/casa/classroom-map-vocabulary.jpg', subject: 'Vocabulary work against a map: hands writing on a Bremen map, no faces. Pool file W006, full frame, modern grade (scripts/media/build_reel.py), 2026-10-02.', ready: true },
  { n: 11, src: '/media/casa/learners-writing-class.jpg', subject: 'Learners writing by hand in class: four learners writing along the table, room above every head. Pool frame 066 (IMG_0265), 5:4 crop, modern grade, scripts/media/build_reel.py. The exams hero. Was 012 until the crop pass of 2026-10-02 (its original frame cuts a crown).', ready: true, position: 'lg:object-[20%_50%] xl:object-[50%_50%]' },
  { n: 12, src: '/media/casa/group-classroom-teacher-activity.jpg', subject: 'Teacher running an activity with the group. Reused across course pages and the About community story; needs to work as a large image and in a small card.', ready: false },
  { n: 13, src: '/media/casa/individual-tutoring.jpg', subject: 'One-to-one support at a desk: one person explaining a worksheet to another. Pool frame 011 (IMG_0021), full 3:2 frame, modern grade, scripts/media/build_reel.py, 2026-10-02. FAQ "Ihre Frage ist noch offen?" and the contact page.', ready: true, position: 'md:object-[50%_8%] lg:object-[50%_50%]' },
  { n: 14, src: '/media/casa/whiteboard-german-coaching.jpg', subject: 'Coaching at the whiteboard, German visibly on the board.', ready: false },
  { n: 15, src: '/media/casa/business-german-group.jpg', subject: 'Professional adults in a workplace-German setting — business dress, meeting-room feel.', ready: false },
  { n: 16, src: '/media/casa/junior-classroom-listening.jpg', subject: 'Younger learners listening — the junior/teen cohort.', ready: false },
  { n: 17, src: '/media/casa/advising-session-classroom.jpg', subject: 'An advising conversation across a desk — two people, one clearly helping the other.', ready: false },
  { n: 18, src: '/media/casa/exam-preparation-writing.jpg', subject: 'Exam-condition writing: a hand writing the telc Deutsch B2 "Schriftlicher Ausdruck (Brief)" sheet. Pool file W007 (older editorial edit, checked at 100-200%: real handwriting and print, no artefacts). 4:3 crop that leaves out the answer sheet\'s date-of-birth boxes and a brochure face, modern grade, scripts/media/build_reel.py, 2026-10-02.', ready: true, position: 'object-[50%_0%] sm:object-[50%_50%] md:object-[50%_0%] xl:object-[50%_50%]' },
  { n: 19, src: '/media/casa/study-materials-map.jpg', subject: 'Study materials laid out with a map.', ready: false },

  // ---- Groups, excursions, Bremen -----------------------------------------
  { n: 20, src: '/media/casa/group-course-bremen-musicians.jpg', subject: 'Group at the Bremen Town Musicians statue. Pool file W008, regraded to the modern set (scripts/media/build_reel.py), 2026-10-02.', ready: true },
  { n: 21, src: '/media/casa/group-course-lunch-table.jpg', subject: 'Group eating together, social rather than instructional: a visiting school group at lunch in the courtyard. Pool file W009 (older editorial edit, checked at 100-200%), full frame; its purple cast and lifted blacks corrected globally, scripts/media/build_reel.py, 2026-10-02.', ready: true, position: 'md:object-[50%_14%] lg:object-[50%_50%]' },
  { n: 22, src: '/media/casa/group-course-phone-task.jpg', subject: 'Learners on a phone-based task out in the city.', ready: false },
  { n: 23, src: '/media/casa/group-course-walking-bremen.jpg', subject: 'Group walking through Bremen together, city legible behind them. Pool file W012, regraded to the modern set (scripts/media/build_reel.py), 2026-10-02.', ready: true, position: 'object-[26%_50%] md:object-[50%_50%]' },
  { n: 24, src: '/media/casa/student-group-activity-outdoor.jpg', subject: 'Outdoor group activity, daylight, clearly not a classroom.', ready: false },
  { n: 25, src: '/media/casa/bremen-schnoor-houses.jpg', subject: 'The Schnoor quarter houses, no people. Pool file W003 (older editorial edit, checked at 100-200%), 5:4 crop, saturation reduced (chroma 0.85), scripts/media/build_reel.py, 2026-10-02.', ready: true, position: '2xl:object-[50%_36%]' },

  // ---- Accommodation -------------------------------------------------------
  { n: 26, src: '/media/casa/student-room-balcony.jpg', subject: 'Student room with a balcony: a room in a CASA-WG with balcony doors, bed and desk. Pool file 003, 4:3 crop, modern grade, scripts/media/build_reel.py, 2026-10-02. A CASA-WG room, never a host family\'s.', ready: true },
  { n: 27, src: '/media/casa/host-family-room.jpg', subject: 'A host family\'s home: the dining table with the open kitchen beyond. Host-family photo 08 (iPhone IMG_7598, Neanderstrasse, resized derivative from the CASA photo package; consent CASA 2026-09-15, cleared for the website by Rahman 2026-10-02). 4:3 crop leaving out a wall display and a bag, white balance from the wall, scripts/media/build_reel.py, 2026-10-02.', ready: true },
  { n: 28, src: '/media/casa/shared-flat-kitchen-table.jpg', subject: 'Shared-flat kitchen table: the kitchen of a CASA-WG. Pool file W013 (older editorial edit, checked at 100-200%); the crop leaves out the wide-angle stretch at both edges, modern grade, scripts/media/build_reel.py, 2026-10-02.', ready: true },
  { n: 29, src: '/media/casa/student-shared-kitchen.jpg', subject: 'A shared kitchen in use.', ready: false },
  { n: 30, src: '/media/casa/student-room-alternative-1.jpg', subject: 'A second, different student room: a single room in a CASA-WG, bed, desk and tulips. Pool file 004, 4:3 crop, modern grade, scripts/media/build_reel.py, 2026-10-02.', ready: true },

  /*
   * ---- Team portraits ----------------------------------------------------
   * UNUSED, AND THAT IS DELIBERATE.
   *
   * The files at these paths are synthetic images that were generated for six
   * invented people — Anna Keller, David Stein, Kareem Yilmaz, Lucas Brandt,
   * Melanie Hoffmann, Sofia Martin — none of whom work at CASA. /team now lists
   * the twelve real colleagues casa-bremen.de publishes, and it renders a
   * monogram for each, because putting a generated face beside a real
   * colleague's name would be a worse misrepresentation than the invented staff
   * were (CLAUDE.md hard rule 3).
   *
   * The numbers stay so the photo brief survives: twelve real portraits, taken
   * with each person's consent, will slot in here. Until then nothing on the site
   * points at these paths. Six numbers were already allocated to this block, so
   * six live here and the other six are appended at the end — this file never
   * reassigns a number (see the test).
   *
   * Same frame for all of them, or the grid reads as separate sittings:
   * head-and-shoulders, consistent eyeline, square crop, plain background, and it
   * has to hold up at 74px.
   */
  { n: 31, src: '/media/casa/team/team-portrait-01.jpg', subject: 'Staff portrait 1 of 12 — a real CASA colleague, consent on file. Square, head and shoulders, plain ground, must hold up at 74px.', ready: false },
  { n: 32, src: '/media/casa/team/team-portrait-02.jpg', subject: 'Staff portrait 2 of 12. Match the framing of 31.', ready: false },
  { n: 33, src: '/media/casa/team/team-portrait-03.jpg', subject: 'Staff portrait 3 of 12. Match the framing of 31.', ready: false },
  { n: 34, src: '/media/casa/team/team-portrait-04.jpg', subject: 'Staff portrait 4 of 12. Match the framing of 31.', ready: false },
  { n: 35, src: '/media/casa/team/team-portrait-05.jpg', subject: 'Staff portrait 5 of 12. Match the framing of 31.', ready: false },
  { n: 36, src: '/media/casa/team/team-portrait-06.jpg', subject: 'Staff portrait 6 of 12. Match the framing of 31. The remaining six are appended at the end of this list, because numbers are never reassigned.', ready: false },

  /*
    ---- Awaited ------------------------------------------------------------
    Numbered but not yet shot. There is no file at this path, and that is the
    point: the slot renders as numbered colour, so the gap is visible on the
    page instead of being hidden behind a borrowed stock-ish photograph.
  */
  {
    n: 37,
    src: '/media/casa/medical-german-consultation.jpg',
    subject:
      'German for Medical. Healthcare professionals practising a patient consultation — scrubs or clinical setting readable, two people talking rather than a lecture. THIS PHOTOGRAPH DOES NOT EXIST YET; the course borrowed a generic advising shot until now.',
    ready: false,
  },

  /*
    The remaining six staff portraits. CASA publishes twelve colleagues and this
    block only had six numbers, so the balance is appended here rather than
    renumbering the list. Same brief as 31.
  */
  { n: 38, src: '/media/casa/team/team-portrait-07.jpg', subject: 'Staff portrait 7 of 12. Match the framing of 31.', ready: false },
  { n: 39, src: '/media/casa/team/team-portrait-08.jpg', subject: 'Staff portrait 8 of 12. Match the framing of 31.', ready: false },
  { n: 40, src: '/media/casa/team/team-portrait-09.jpg', subject: 'Staff portrait 9 of 12. Match the framing of 31.', ready: false },
  { n: 41, src: '/media/casa/team/team-portrait-10.jpg', subject: 'Staff portrait 10 of 12. Match the framing of 31.', ready: false },
  { n: 42, src: '/media/casa/team/team-portrait-11.jpg', subject: 'Staff portrait 11 of 12. Match the framing of 31.', ready: false },
  { n: 43, src: '/media/casa/team/team-portrait-12.jpg', subject: 'Staff portrait 12 of 12. Match the framing of 31.', ready: false },

  // ---- Append new photographs below this line, next number, never resort --
  { n: 44, src: '/media/casa/casa-building-golden.webp', subject: 'AI-PROCESSED, DO NOT USE (go-live brief 2026-10-01): the golden version misspells the window sign and changes the windows. Was: CASA building in golden evening light. User-supplied processed image approved for local website preview on 2026-09-21.', ready: false },
  { n: 45, src: '/media/casa/casa-building-daylight.webp', subject: 'AI-PROCESSED, DO NOT USE (go-live brief 2026-10-01): the golden version misspells the window sign and changes the windows. Was: CASA building in clear daylight. User-supplied processed image approved for local website preview on 2026-09-21.', ready: false },
  { n: 46, src: '/media/casa/reel-learning-together-wide.webp', subject: 'Retired 2026-09-23. Was an AI-redrawn panorama of collection frame 085 (faces and surroundings regenerated); the file is deleted and the number is not reused.', ready: false },
  { n: 47, src: '/media/casa/reel-language-practice-wide.webp', subject: 'Retired 2026-09-23. Was an AI-redrawn panorama of collection frame 021; the file is deleted and the number is not reused.', ready: false },
  { n: 48, src: '/media/casa/reel-garden-gathering-wide.webp', subject: 'Retired 2026-09-23. Was an AI-redrawn panorama of collection frame 095 (people moved and redrawn); the file is deleted and the number is not reused. The team photograph in 53 took its place.', ready: false },
  { n: 49, src: '/media/casa/reel-building-golden-wide.webp', subject: 'Retired 2026-09-23. Was an AI panorama of the facade that invented neighbouring houses and misspelled the window sign; the file is deleted and the number is not reused. A real building photograph gets a new number.', ready: false },
  { n: 50, src: '/media/casa/reel-walking-bremen-wide.webp', subject: 'Students walking together in Bremen. The slot 23 photograph (collection W012), cropped 2:1 with light correction only (scripts/media/build_reel.py), 2026-09-23.', ready: true },
  { n: 51, src: '/media/casa/reel-classroom-lesson.webp', subject: 'A lesson in progress: the teacher laughing with a worksheet, a learner at the board, German grammar in the teacher\'s handwriting. Collection frame 093, cropped 2:1 with light correction only, 2026-09-23.', ready: true },
  { n: 52, src: '/media/casa/reel-partner-practice.webp', subject: 'Two learners doing a partner interview from a worksheet, talking and smiling. Collection frame 075, cropped 2:1 with light correction only, 2026-09-23.', ready: true },
  { n: 53, src: '/media/casa/reel-team-courtyard.webp', subject: 'The CASA team standing together in the leafy courtyard, most smiling at the camera. Collection frame 098, cropped 2:1 with light correction only, 2026-09-23.', ready: true },
  { n: 54, src: '/media/casa/hero-classroom-lesson.webp', subject: 'The slot 51 lesson as a 5:4 crop of the full frame (collection 093, 2110x1688), light correction only (scripts/media/build_reel.py), for the half-width homepage hero, 2026-10-01.', ready: true, position: 'lg:object-[40%_50%] xl:object-[50%_50%]' },
  { n: 55, src: '/media/casa/about-team-courtyard.webp', subject: 'The slot 53 team photograph as the whole 3:2 frame (collection 098, 2560x1706), light correction only (scripts/media/build_reel.py), for the About hero, 2026-10-01.', ready: true },
  { n: 56, src: '/media/casa/home-class-welcome.webp', subject: 'The homepage\'s "Wir hören zu": the teacher with smiling learners at the course table. Collection frame 087, 3:2 crop, modern grade (scripts/media/build_reel.py), 2026-10-02.', ready: true },
  { n: 57, src: '/media/casa/casa-wg-room.webp', subject: 'A single room in a CASA shared flat: bed, armchair, desk, the navy wall. Collection file 008, 4:3 crop with light correction only (scripts/media/build_reel.py), for the homepage accommodation block, 2026-10-01. Not a host-family room.', ready: true },
  { n: 58, src: '/media/casa/course-intensive-hero.webp', subject: 'Intensivkurse course-page hero: frame 060 as a 2.4:1 band composed for the hero, modern grade, 2026-10-02.', ready: true },
  { n: 59, src: '/media/casa/course-intensive-story.webp', subject: 'Intensivkurse second photo: the same class (frame 061), the teacher presenting at the screen, modern grade, 2026-10-02.', ready: true },
  { n: 60, src: '/media/casa/course-evening-hero.webp', subject: 'Abendkurse course-page hero: frame 088 as a 2.4:1 band, modern grade, 2026-10-02.', ready: true },
  { n: 61, src: '/media/casa/course-special-hero.webp', subject: 'Spezialkurse course-page hero: frame 067 as a 2.4:1 band, modern grade, 2026-10-02.', ready: true },
  { n: 62, src: '/media/casa/course-bildungszeit-class.webp', subject: 'Bildungszeit: a learner smiling up from his exercise while the teacher writes grammar on the board. Frame 094, 4:3 crop, modern grade, 2026-10-02.', ready: true, position: 'lg:object-[50%_24%] xl:object-[50%_50%]' },
  { n: 63, src: '/media/casa/course-bildungszeit-hero.webp', subject: 'Bildungszeit course-page hero: frame 094 as a 2.4:1 band, modern grade, 2026-10-02.', ready: true },
  { n: 64, src: '/media/casa/course-company-classroom.webp', subject: 'Retired 2026-10-08. Was Firmenunterricht\'s photo: an empty CASA classroom (frame 053), which Rahman found was not the right picture for the course; slots 84-86 replaced it. The file is deleted and the number is not reused.', ready: false },
  { n: 65, src: '/media/casa/course-company-hero.webp', subject: 'Retired 2026-10-08. Was the same empty classroom as Firmenunterricht\'s hero band; slot 85 replaced it. The file is deleted and the number is not reused.', ready: false },
  { n: 66, src: '/media/casa/exam-b2-hero.webp', subject: 'telc B2 page hero from lg up: the W007 writing hand as a 2.4:1 band (1370px wide, the most the frame has), modern grade, 2026-10-02.', ready: true, position: 'md:object-[50%_32%]' },
  { n: 67, src: '/media/casa/exam-b2-class.webp', subject: 'telc B2 page second photo: two learners going through their papers. Pool frame 079 (IMG_0286), full frame, modern grade. Was 023 until the crop pass of 2026-10-02 (its original frame cuts two heads).', ready: true },
  { n: 68, src: '/media/casa/exam-c1-writing.webp', subject: 'Retired 2026-10-08. Was the telc C1 Hochschule photo on phones: three learners from the row in frame 065; slot 92 replaced it. The file is deleted and the number is not reused.', ready: false },
  { n: 69, src: '/media/casa/exam-c1-hero.webp', subject: 'Retired 2026-10-08. Was the telc C1 Hochschule hero band, a row of five learners (frame 065), which did not look good in the hero; slot 93 replaced it. The file is deleted and the number is not reused.', ready: false },
  { n: 70, src: '/media/casa/exam-c1-speaking.webp', subject: 'telc C1 Hochschule page second photo: two learners discussing a text. Pool frame 074 (IMG_0278), full frame, modern grade. Was 031 until the crop pass of 2026-10-02 (hair touching the frame top).', ready: true },
  { n: 71, src: '/media/casa/exam-story-writing.webp', subject: 'The exams page\'s candidate story: two learners reading their exam texts. Pool frame 078 (IMG_0285), full frame, modern grade. Was 024 until the crop pass of 2026-10-02 (blurred heads cut by the frame top).', ready: true },
  /*
   * HOST-FAMILY IMAGES (27, 72-77, 81): to be replaced by AI-generated
   * illustrations made from these photographs (Rahman, 2026-10-08), the one
   * exception to hard rule 4. docs/HOST_FAMILY_IMAGES.md is the brief.
   */
  { n: 72, src: '/media/casa/host-family-living-hero.webp', subject: 'Host-family page hero from lg up: host-family photo 08 (the slot 27 room) as a 2.4:1 band, 2026-10-02.', ready: true },
  { n: 73, src: '/media/casa/host-family-kitchen.webp', subject: 'A host family\'s kitchen. Host-family photo 09 (iPhone IMG_7599, resized derivative; consent CASA 2026-09-15, website use cleared 2026-10-02), 3:2 crop leaving out a coat, white balance from the wall, 2026-10-02.', ready: true },
  { n: 74, src: '/media/casa/host-family-kitchen-detail.webp', subject: 'A host family\'s kitchen from the other side, the sewing-machine table between the windows. Host-family photo 12 (iPhone 15 original IMG_7601), 3:2 crop that leaves out a wall of family photographs, scaled to 2560px, 2026-10-02.', ready: true },
  { n: 75, src: '/media/casa/host-family-kitchen-hero.webp', subject: 'Become-a-host hero from lg up: host-family photo 12 as a 2.4:1 band, scaled to 2560px, 2026-10-02.', ready: true },
  { n: 76, src: '/media/casa/host-family-guest-bathroom.webp', subject: 'A host family\'s guest bathroom. Host-family photo 10 (iPhone IMG_7602, resized derivative), 3:2 crop below the mirror, 2026-10-02.', ready: true },
  { n: 77, src: '/media/casa/host-family-dining-table.webp', subject: 'A host family\'s dining table. Host-family photo 11 (iPhone 15 original IMG_7596); the crop starts below the windowsills (framed photographs of the family\'s children) and stays left of a pinboard of letters, 2026-10-02.', ready: true },
  { n: 78, src: '/media/casa/casa-wg-room-hero.webp', subject: 'CASA-WG page hero from lg up: pool file 004 (the slot 30 room) as a 2.4:1 band, modern grade, 2026-10-02.', ready: true },
  { n: 79, src: '/media/casa/community-shared-meal.webp', subject: 'Learners and volunteers sharing a breakfast table in a CASA classroom, one playing the guitar. Pool frame 043 (IMG_0178), the whole 3:2 frame, modern grade, 2026-10-02.', ready: true },
  { n: 80, src: '/media/casa/study-learners-dictionary.webp', subject: 'Retired 2026-10-02 (crop pass): was pool frame 034, whose original frame cuts a learner\'s crown; the file is deleted and the number is not reused. The Studieren hero is slot 82.', ready: false },
  { n: 81, src: '/media/casa/host-family-guest-room.jpg', subject: 'A guest room in a host family: bed, desk, wardrobe, a lamp. THIS PHOTOGRAPH DOES NOT EXIST YET; the host-family photo set (2026-09-15) has living room, kitchen and bathrooms but no guest room, and a CASA-WG room must not stand in for it (hard rule 5).', ready: false },
  { n: 82, src: '/media/casa/study-learners-attentive.webp', subject: 'The "Studieren in Deutschland" hero: two learners listening attentively. Pool frame 026 (IMG_0185), the whole 5:4 frame, modern grade, white balance half-corrected (cream wall, tungsten), 2026-10-02.', ready: true, position: 'sm:object-[50%_4%] md:object-[50%_2%] lg:object-[22%_50%] xl:object-[50%_14%] 2xl:object-[50%_6%]' },
  { n: 83, src: '/media/casa/home-community-breakfast.webp', subject: 'The homepage\'s "community events" tile: a learner clapping at the shared breakfast (the slot 79 morning). Pool frame 050 (IMG_0194), a portrait crop, modern grade, 2026-10-02.', ready: true, position: 'object-[50%_22%] lg:object-[50%_50%] xl:object-[50%_32%]' },
  /*
   * THE SECOND PASS (2026-10-08): Firmenunterricht shows people at work instead
   * of an empty classroom, the C1 Hochschule hero is new, and the medical
   * course, Bildungszeit and the team page have photographs where a stand-in or
   * the empty room was. Only frames whose people Rahman confirmed: 076 and 077
   * (2026-10-01), 061 (2026-10-02), 012, 023, 024, 031 and 032 (the brief).
   * Crop and the warm editorial grade only (scripts/media/build_reel.py).
   */
  { n: 84, src: '/media/casa/course-company-colleagues.webp', subject: 'Firmenunterricht: two colleagues going through a document. Pool frame 076 (IMG_0283), 4:3 crop, warm editorial grade, 2026-10-08.', ready: true },
  { n: 85, src: '/media/casa/course-company-colleagues-hero.webp', subject: 'Firmenunterricht course-page hero from lg up: frame 076 as a 2.4:1 band, warm editorial grade, 2026-10-08.', ready: true },
  { n: 86, src: '/media/casa/course-company-focus.webp', subject: 'Firmenunterricht second photo: a learner reading closely, a colleague beside her. Pool frame 032 (IMG_0473), full frame, 2026-10-08.', ready: true, position: 'md:object-[50%_2%] lg:object-[50%_50%]' },
  { n: 87, src: '/media/casa/course-company-writing.webp', subject: 'Beside a Firmenunterricht participant\'s quote: a hand with a pen, the class out of focus behind it, so no face can be read as the person quoted (hard rule 2). Pool frame 024 (IMG_0156), full frame, 2026-10-08.', ready: true, position: 'object-[80%_50%] md:object-[50%_68%] lg:object-[50%_50%]' },
  { n: 88, src: '/media/casa/course-medical-dialogue.webp', subject: 'Deutsch für Pflege und Medizin, until a clinical photograph exists (slot 37): two learners going through a text together. Pool frame 077 (IMG_0284), 4:3 crop, warm editorial grade, 2026-10-08.', ready: true },
  { n: 89, src: '/media/casa/course-medical-dialogue-hero.webp', subject: 'The medical course page hero from lg up: frame 077 as a 2.4:1 band, warm editorial grade, 2026-10-08.', ready: true },
  { n: 90, src: '/media/casa/course-medical-writing.webp', subject: 'The medical course page second photo: two learners writing. Pool frame 012 (IMG_0031), full frame, 2026-10-08.', ready: true, position: 'md:object-[50%_32%] lg:object-[50%_50%]' },
  { n: 91, src: '/media/casa/course-bildungszeit-learner.webp', subject: 'Bildungszeit second photo (was the empty classroom of slot 64): a learner smiling across the table, his books in front of him. Pool frame 031 (IMG_0472), full frame, 2026-10-08.', ready: true, position: 'md:object-[50%_2%] lg:object-[50%_50%]' },
  { n: 92, src: '/media/casa/exam-c1-study.webp', subject: 'telc C1 Hochschule on phones: three learners writing in a row. Pool frame 023 (IMG_0147), 4:3 crop, 2026-10-08.', ready: true, position: 'lg:object-[50%_20%]' },
  { n: 93, src: '/media/casa/exam-c1-study-hero.webp', subject: 'The telc C1 Hochschule hero band from lg up: frame 023 as a 2.4:1 band, 2026-10-08.', ready: true, position: 'md:object-[50%_32%]' },
  { n: 94, src: '/media/casa/team-lesson-wide.webp', subject: 'The team page\'s "Wer wir sind": a teacher at the screen with her class, the whole frame of 061 (slot 59 is a close crop of it), warm editorial grade, 2026-10-08.', ready: true },
];

const slotsBySrc = new Map(photoSlots.map((slot) => [slot.src, slot]));

/**
 * What a slot is ABOUT, by the brand's colour meanings (src/config/brand/meaning.ts).
 * A slot with no photograph yet renders a calm panel in this colour with its icon
 * (src/components/ui/casa-image.tsx) instead of a gradient with a number.
 */
export function photoMeaningFor(n: number | undefined): Meaning {
  if (n === undefined) return 'orientation';
  if (n === 18) return 'exams';
  if (n === 17) return 'orientation';
  // 21 sits with the excursions but is the groups course's photograph.
  if ((n >= 4 && n <= 19) || n === 21 || n === 37) return 'courses';
  if ((n >= 26 && n <= 30) || n === 81) return 'arrival';
  return 'orientation';
}

/** The slot for a photograph path, or undefined if it has no number yet. */
export function photoSlotFor(src: string): PhotoSlot | undefined {
  return slotsBySrc.get(src);
}
