import type { ContentLocale, ProofMetric } from '@/lib/content/types';

export const proofMetricsByLocale: Record<ContentLocale, ProofMetric[]> = {
  en: [
    {
      value: 'Since 1983',
      label: 'Independent language school in Bremen',
      locale: 'en',
      sourceUrl: 'https://www.casa-bremen.de/unsere-sprachschule/',
      sourceType: 'website',
      verificationStatus: 'verified',
      asOf: '2026-02-09',
    },
    {
      value: '30,000+',
      label: 'Learners supported over the years',
      locale: 'en',
      sourceUrl: 'internal-dashboard-aggregate:2026-06-17',
      sourceType: 'internal',
      verificationStatus: 'verified',
      asOf: '2026-06-17',
    },
    {
      value: '150+ countries',
      label: 'Students represented in CASA classrooms',
      locale: 'en',
      sourceUrl: 'internal-dashboard-aggregate:2026-06-17',
      sourceType: 'internal',
      verificationStatus: 'verified',
      asOf: '2026-06-17',
    },
    {
      value: '40+ staff & teachers',
      label: 'Academic and administrative team',
      locale: 'en',
      sourceUrl: 'https://www.casa-bremen.de/unsere-sprachschule/',
      sourceType: 'internal',
      verificationStatus: 'draft',
      asOf: '2026-02-09',
    },
  ],
  de: [
    {
      value: 'Seit 1983',
      label: 'Unabhängige Sprachschule in Bremen',
      locale: 'de',
      sourceUrl: 'https://www.casa-bremen.de/unsere-sprachschule/',
      sourceType: 'website',
      verificationStatus: 'verified',
      asOf: '2026-02-09',
    },
    {
      value: '30.000+',
      label: 'Begleitete Lernende über die Jahre',
      locale: 'de',
      sourceUrl: 'internal-dashboard-aggregate:2026-06-17',
      sourceType: 'internal',
      verificationStatus: 'verified',
      asOf: '2026-06-17',
    },
    {
      value: '150+ Herkunftsländer',
      label: 'Vertretene Nationen in den CASA-Kursen',
      locale: 'de',
      sourceUrl: 'internal-dashboard-aggregate:2026-06-17',
      sourceType: 'internal',
      verificationStatus: 'verified',
      asOf: '2026-06-17',
    },
    {
      value: '40+ Mitarbeitende',
      label: 'Lehrkräfte und Verwaltung im Team',
      locale: 'de',
      sourceUrl: 'https://www.casa-bremen.de/unsere-sprachschule/',
      sourceType: 'internal',
      verificationStatus: 'draft',
      asOf: '2026-02-09',
    },
  ],
};
